"""Deterministic synthetic pack generator for `lab/twin-bfms` (BUILD-SPEC 4).

    PYTHONPATH=src .venv/bin/python lab/twin-bfms/labkit/generate_pack.py --scenario <path> [--out <dir>]
    PYTHONPATH=src .venv/bin/python lab/twin-bfms/labkit/generate_pack.py --all            # three packs + packs/_pins.json
    PYTHONPATH=src .venv/bin/python lab/twin-bfms/labkit/generate_pack.py --bondi-reference # fixtures/bondi-reference/

Everything under `packs/<deal_id>/` is text (md/txt/csv/json), stamped by `labkit.provenance`
(the only writer) and listed in `PACK-MANIFEST.json`. Two runs are byte-identical: no clock,
no randomness, no absolute paths in any envelope.

What is reused, read-only, via importlib (never edited, never executed as a script):
- `fulfillment/demo/build_fixtures.py`: DOCUMENTS, APPROVED_FIELDS, APPROVED, APPROVAL_NOTE,
  VAULT, REF (the closing-binder excerpts and the approved obligation rows);
- `fulfillment/demo/run.py`: `period_tokens` (the demo's own evidence-file labelling).

What is generated by the lab: the intake `.txt` files (one per housing RequiredArtifact, one
`<Label>: <value>` line per `lab.intake_facts` path), the document-request checklist, the
intake manifest, and the BONDI-format `bondi/` emission (`labkit.events`).

Readability self-check (critic M4): before anything is written, every intake artifact is
run through the offline `RulesBasedExtractor` on its own (one job per artifact, target paths
= that artifact's paths, chunk text = envelope + legend + body exactly as uploaded); every
path must round-trip to its `intake_facts` value or the generator refuses to write. Line
order inside a file is chosen by a deterministic topological sort so that the first line
matching a path's labels is that path's own line.

The MSRB platform token (DEC-008) survives exactly once per pack, on the Rule 15c2-12
Section 4(a) line of the CDA excerpt; the demo's other occurrences (OB-01 text, five
recipients, one vault recipient) are scrubbed mechanically at re-emission.
"""

from __future__ import annotations

import sys

# Run as a script, Python puts THIS directory (labkit/) first on sys.path, where
# `labkit/types.py` would shadow the stdlib `types` module. Strip it before any other
# import; put the program root (lab/twin-bfms) there instead so `labkit.*` resolves.
_SELF_DIR = __file__.replace("\\", "/").rsplit("/", 1)[0]
sys.path[:] = [
    p for p in sys.path if p not in ("", ".") and p.replace("\\", "/").rstrip("/") != _SELF_DIR
]
_PROGRAM_ROOT = _SELF_DIR.rsplit("/", 1)[0]
if _PROGRAM_ROOT not in sys.path:  # tests reach labkit through tests/lab_support.py
    sys.path.insert(0, _PROGRAM_ROOT)

import argparse  # noqa: E402
import ast  # noqa: E402
import importlib.util  # noqa: E402
import json  # noqa: E402
import re  # noqa: E402
import shutil  # noqa: E402
from dataclasses import dataclass, field  # noqa: E402
from pathlib import Path  # noqa: E402
from types import ModuleType  # noqa: E402
from typing import Any  # noqa: E402

from labkit import events as events_mod  # noqa: E402
from labkit import law  # noqa: E402
from labkit import names as names_mod  # noqa: E402
from labkit import scenario as scenario_mod  # noqa: E402
from labkit.provenance import (  # noqa: E402
    PackManifest,
    ProvenanceViolation,
    WrittenFile,
    sha256_bytes,
    sha256_file,
    sha256_text,
    write_csv,
    write_json,
    write_md,
    write_txt,
    write_vault_txt,
)
from labkit.types import Envelope  # noqa: E402
from munipal.services.extraction.rules_based_extractor import (  # noqa: E402
    _SCHEMA_BY_PATH,
    RulesBasedExtractor,
)
from munipal.services.pilot_onboarding import (  # noqa: E402
    _OPERATOR_WORKSPACE_FOLDERS,
    build_pilot_onboarding_workflow,
)

# --------------------------------------------------------------------------------------
# Paths and constants
# --------------------------------------------------------------------------------------

LAB_ROOT: Path = law.LAB_ROOT
REPO_ROOT: Path = LAB_ROOT.parents[1]
PACKS_DIR: Path = LAB_ROOT / "packs"
PINS_PATH: Path = PACKS_DIR / "_pins.json"
FIXTURES_DIR: Path = LAB_ROOT / "fixtures" / "bondi-reference"
FORMAT_JSON_PATH: Path = FIXTURES_DIR / "format.json"
FORMAT_PROVENANCE_PATH: Path = FIXTURES_DIR / "PROVENANCE.md"
DEMO_DIR: Path = REPO_ROOT / "fulfillment" / "demo"
BUILD_FIXTURES_PATH: Path = DEMO_DIR / "build_fixtures.py"
RUN_PY_PATH: Path = DEMO_DIR / "run.py"
BONDI_GENERATE_REL = "synth-issuance/generate.py"
BONDI_GENERATE_WINDOWS_PATH = (
    r"C:\Users\st3ja\OneDrive\Documents\MEGA\PROJECTS\INNOVATION FACTORY\APPLIED RESEARCH"
    r"\bondi-bfms\synth-issuance\generate.py"
)
#: Date literal of the transcription (a provenance record, not a scenario date).
TRANSCRIPTION_DATE = "2026-09-10"

COMMITTED_SCENARIOS: tuple[str, ...] = (
    "SYN-HSG-AZ-2025-LAB01",
    "SYN-HSG-AZ-2025-LAB02",
    "SYN-HSG-AZ-2025-LAB03",
)

INTAKE_DIR = "intake"
WELCOME_FOLDER = "00_WELCOME"
CLOSING_DIR = "closing-documents"
POST_CLOSE_DIR = "post-close"
VAULT_DIR = "vault"
#: Operator workspace folder per housing RequiredArtifact (pilot_onboarding.py:128-137).
FOLDER_BY_ARTIFACT: dict[str, str] = {
    "issuer_borrower_authority": "01_PROJECT-OVERVIEW",
    "subsidy_stack": "02_FINANCING-STRUCTURE",
    "rent_roll_operating": "02_FINANCING-STRUCTURE",
    "site_control_permits": "03_DUE-DILIGENCE",
    "market_compliance": "03_DUE-DILIGENCE",
}
#: Paths whose round-trip is compared as an integer (currency in SCHEMA_PATHS; F12).
INT_COMPARED_PATHS: frozenset[str] = frozenset({"capital.project-cost"})
#: Decorative pipe table for rent_roll_operating (exercises `_value_from_pipe_row`; rows
#: never carry a target label). Units sum to the `housing.units.total` value.
RENT_ROLL_TABLE: tuple[str, ...] = (
    "| Unit type | Units | Monthly rent |",
    "|---|---|---|",
    "| One-bedroom | 40 | $1,180 |",
    "| Two-bedroom | 68 | $1,410 |",
    "| Three-bedroom | 24 | $1,625 |",
    "| Accessible one-bedroom | 12 | $1,180 |",
)
#: Vault evidence patterns that the late_afs knob suspends (BUILD-SPEC 3.4: OB-01/09/10).
AFS_LINKED_PATTERNS: frozenset[str] = frozenset({"annual-report-FY{fy}", "afs-FY{fy}", "dscr-calc-FY{fy}"})
#: deal_workflow `_STANDARD_DOCUMENTS` the scenario does not carry as documents (4.2).
STANDARD_DOCS_NOT_CARRIED: tuple[tuple[str, str], ...] = (
    ("form_8038", "no document carried; tax.form_8038.filed is a scenario date only"),
    ("plom", "no document carried; limited offering, preliminary memorandum not in pack"),
    ("limited_offering_memorandum", "no document carried; instrument.document_type names it, text not in pack"),
    ("investor_letters", "no document carried; stations.5_buyers investment_letters is a log row only"),
    ("closing_memo", "no document carried"),
    ("signature_pages", "no document carried"),
)


class PackError(ValueError):
    """The generator refused to write (self-check or law violation)."""


# --------------------------------------------------------------------------------------
# Read-only imports of the demo modules
# --------------------------------------------------------------------------------------


def load_module(path: Path, name: str) -> ModuleType:
    """Import a script file read-only (module-level constants only; `main()` never called)."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise PackError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def demo_modules() -> tuple[ModuleType, ModuleType]:
    bf = load_module(BUILD_FIXTURES_PATH, "lab_demo_build_fixtures")
    run = load_module(RUN_PY_PATH, "lab_demo_run")
    for attr in ("DOCUMENTS", "APPROVED_FIELDS", "APPROVED", "APPROVAL_NOTE", "VAULT", "REF"):
        if not hasattr(bf, attr):
            raise PackError(f"build_fixtures.py lacks {attr}")
    if not hasattr(run, "period_tokens") or not hasattr(run, "STATUSES"):
        raise PackError("run.py lacks period_tokens / STATUSES")
    return bf, run


# --------------------------------------------------------------------------------------
# MSRB platform-token scrub (DEC-008)
# --------------------------------------------------------------------------------------

_VIA_TOKEN_RE = re.compile(r" via " + law.EMMA_WORD.pattern)
_PAREN_TOKEN_RE = re.compile(r"\s*\(" + law.EMMA_WORD.pattern + r"\)")


def scrub_platform_token(text: str) -> str:
    """Remove ` via <token>` and ` (<token>)`; refuse if the token survives."""
    out = _PAREN_TOKEN_RE.sub("", _VIA_TOKEN_RE.sub("", text))
    if law.EMMA_WORD.search(out):
        raise PackError(f"platform token survives scrub: {text!r}")
    return out


# --------------------------------------------------------------------------------------
# Intake generation + readability self-check
# --------------------------------------------------------------------------------------

_extractor = RulesBasedExtractor()


def schema_for(path: str) -> dict[str, Any]:
    return _SCHEMA_BY_PATH.get(path, {"path": path, "value_type": "string"})


def labels_for(path: str) -> tuple[str, ...]:
    return _extractor._labels_for_path(path, schema_for(path))


def label_for(path: str) -> str:
    """The FIRST extractor label for `path`, capitalised (BUILD-SPEC 4.1)."""
    first = labels_for(path)[0]
    return first[0].upper() + first[1:]


def expected_value(path: str, value: str) -> Any:
    if path in INT_COMPARED_PATHS:
        return int(re.sub(r"[^\d]", "", value))
    return value


def _extract_one(text: str, path: str) -> Any:
    facts = _extractor.extract([{"id": "self-check", "text_content": text}], [path])
    return facts[0].value if facts else None


def order_lines(paths: list[str], facts: dict[str, str], fixed_prefix: list[str]) -> list[str]:
    """Order `paths` so each path's own line is the first match for its labels.

    Constraint: if the line of A yields a WRONG value for B, B's line must precede A's.
    Kahn's algorithm with the scenario order as the tie-break; a cycle refuses the pack.
    `fixed_prefix` (envelope + legend) cannot be reordered, so it must yield nothing wrong.
    """
    line_of = {p: f"{label_for(p)}: {facts[p]}" for p in paths}
    for p in paths:
        for fixed in fixed_prefix:
            got = _extract_one(fixed, p)
            if got is not None and got != expected_value(p, facts[p]):
                raise PackError(f"fixed line {fixed!r} would hijack {p} (got {got!r})")
    must_precede: dict[str, set[str]] = {p: set() for p in paths}  # b -> {a}: b before a
    for a in paths:
        for b in paths:
            if a == b:
                continue
            got = _extract_one(line_of[a], b)
            if got is not None and got != expected_value(b, facts[b]):
                must_precede[b].add(a)
    ordered: list[str] = []
    remaining = list(paths)
    while remaining:
        ready = [p for p in remaining if not any(q in remaining for q in _predecessors(p, must_precede))]
        if not ready:
            raise PackError(f"label collision cycle among {remaining}; cannot order lines")
        nxt = ready[0]
        ordered.append(nxt)
        remaining.remove(nxt)
    return ordered


def _predecessors(p: str, must_precede: dict[str, set[str]]) -> set[str]:
    return {b for b, afters in must_precede.items() if p in afters}


@dataclass
class IntakeFile:
    order: int
    artifact_key: str
    display_name: str
    requirement_level: str
    folder: str
    relpath: str
    paths: list[str]
    labels: dict[str, str]
    body_lines: list[str]
    text: str = ""
    sha256: str = ""


def readability_check(files: list[IntakeFile], facts: dict[str, str]) -> list[str]:
    """Per-artifact extractor round-trip (M4). Empty list == every path round-trips."""
    problems: list[str] = []
    all_labels = {lbl for f in files for p in f.paths for lbl in labels_for(p)}
    env_keys = ("source", "generator_version", "lab_version", "scenario_id", "seed", "sha256_body", "created_from")
    for key in env_keys:
        norm = _extractor._normalize_label(key)
        for lbl in all_labels:
            if lbl in norm:
                problems.append(f"envelope key {key!r} contains target label {lbl!r}")
    for f in files:
        got = _extractor.extract([{"id": f.relpath, "text_content": f.text}], f.paths)
        by_path: dict[str, list[Any]] = {}
        for fact in got:
            by_path.setdefault(fact.schema_path, []).append(fact.value)
        for p in f.paths:
            vals = by_path.get(p, [])
            want = expected_value(p, facts[p])
            if len(vals) != 1:
                problems.append(f"{f.relpath}: {p} yielded {len(vals)} facts, want 1")
            elif vals[0] != want:
                problems.append(f"{f.relpath}: {p} round-trips to {vals[0]!r}, want {want!r}")
    return problems


def _build_intake(sc: scenario_mod.Scenario, envelope: Envelope) -> list[IntakeFile]:
    playbook = build_pilot_onboarding_workflow(str(sc.lab["sector_playbook_key"])).playbook
    by_key = {a.artifact_key: a for a in playbook.required_artifacts}
    facts = sc.intake_facts
    files: list[IntakeFile] = []
    order = 0
    for artifact_key, paths in sc.intake_docs.items():
        if artifact_key not in by_key:
            raise PackError(f"intake_docs names {artifact_key!r}, not a housing RequiredArtifact")
        folder = FOLDER_BY_ARTIFACT.get(artifact_key)
        if folder is None or folder not in _OPERATOR_WORKSPACE_FOLDERS:
            raise PackError(f"no operator workspace folder for {artifact_key!r}")
        art = by_key[artifact_key]
        relpath = f"{INTAKE_DIR}/{folder}/{artifact_key}.txt"
        env = envelope.model_copy(
            update={"created_from": [f"scenario:{sc.deal_id}#lab.intake_docs.{artifact_key}"]}
        )
        fixed_prefix = [f"# {line}" for line in env.as_lines()] + [law.LEGEND]
        ordered = order_lines(list(paths), facts, fixed_prefix)
        labels = {p: label_for(p) for p in ordered}
        body_lines: list[str] = []
        seen: set[str] = set()
        for p in ordered:
            line = f"{labels[p]}: {facts[p]}"
            if line in seen:
                continue  # identical label+value (F5 twin spellings) -> one line serves both
            seen.add(line)
            body_lines.append(line)
        if artifact_key == "rent_roll_operating":
            for row in RENT_ROLL_TABLE:
                for p in ordered:
                    if _extract_one(row, p) is not None:
                        raise PackError(f"pipe row {row!r} carries a target label for {p}")
            body_lines += ["", *RENT_ROLL_TABLE]
        order += 1
        files.append(
            IntakeFile(
                order=order,
                artifact_key=artifact_key,
                display_name=art.display_name,
                requirement_level=art.requirement_level,
                folder=folder,
                relpath=relpath,
                paths=list(ordered),
                labels=labels,
                body_lines=body_lines,
            )
        )
    for f in files:
        env = envelope.model_copy(
            update={"created_from": [f"scenario:{sc.deal_id}#lab.intake_docs.{f.artifact_key}"]}
        )
        body = "\n".join(f.body_lines)
        env = env.model_copy(update={"sha256_body": sha256_text(body)})
        f.text = "\n".join([f"# {line}" for line in env.as_lines()] + [law.LEGEND] + f.body_lines) + "\n"
    problems = readability_check(files, facts)
    if problems:
        raise PackError("readability self-check failed; refusing to write: " + "; ".join(problems))
    return files


def _document_request_rows(sc: scenario_mod.Scenario, files: list[IntakeFile]) -> list[dict[str, str]]:
    workflow = build_pilot_onboarding_workflow(str(sc.lab["sector_playbook_key"]))
    playbook = workflow.playbook
    key_by_display = {a.display_name: a.artifact_key for a in playbook.required_artifacts}
    file_by_key = {f.artifact_key: f for f in files}
    rows: list[dict[str, str]] = []
    for item in workflow.document_request_list:
        m = re.match(r"^(.*) \((required|recommended)\)$", item)
        if not m or m.group(1) not in key_by_display:
            raise PackError(f"document_request_list entry {item!r} maps to no required_artifacts row")
        key = key_by_display[m.group(1)]
        f = file_by_key.get(key)
        if f is not None:
            status = f"present ({f.relpath})"
        elif key in sc.dropped_artifacts:
            status = "absent_by_scenario (knob drop_required_artifact)"
        else:
            status = "absent (not carried by scenario)"
        rows.append({"request": item, "artifact_key": key, "level": m.group(2), "status": status})
    return rows


# --------------------------------------------------------------------------------------
# Pack generation
# --------------------------------------------------------------------------------------


@dataclass
class GenerateResult:
    deal_id: str
    pack_root: Path
    manifest_path: Path
    manifest_sha256: str
    files_written: int
    intake_files: int
    vault_files: int
    absent_by_scenario: list[dict[str, Any]] = field(default_factory=list)
    intake_paths_unknown: list[str] = field(default_factory=list)


def _emma_allowance(relpath: str) -> tuple[int, str | None]:
    for allowed_rel, heading, count in law.EMMA_ALLOWLIST:
        if allowed_rel == relpath:
            return count, heading
    return 0, None


def _assert_token_under_heading(text: str, heading: str, count: int, where: str) -> None:
    lines = text.split("\n")
    start = next((i for i, line in enumerate(lines) if line.startswith(heading)), None)
    if start is None:
        raise PackError(f"{where}: heading starting {heading!r} not found")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    inside = sum(len(law.EMMA_WORD.findall(line)) for line in lines[start + 1 : end])
    if inside != count:
        raise PackError(f"{where}: {inside} platform-token line(s) under {heading!r}, pinned {count}")


def _vault_name_map(bf: ModuleType, run: ModuleType) -> dict[str, tuple[str, str, str, dict[str, str]]]:
    """rendered evidence-file stem -> (obligation_id, pattern, due ISO, tokens).

    This is the demo's OWN labelling: `approved-inputs.csv` `evidence_pattern` rendered
    with `run.py::period_tokens` for each approved due date. It is not a computed
    obligation date; the due dates are the counsel-approved literals in the csv.
    """
    from datetime import date as _date

    out: dict[str, tuple[str, str, str, dict[str, str]]] = {}
    for row in bf.APPROVED:
        rec = dict(zip(bf.APPROVED_FIELDS, row, strict=True))
        pattern = rec["evidence_pattern"]
        if not pattern:
            continue
        for due in [d for d in rec["due_dates_approved"].split(";") if d.strip()]:
            tokens = run.period_tokens(_date.fromisoformat(due))
            out[pattern.format(**tokens)] = (rec["obligation_id"], pattern, due, tokens)
    return out


def generate(scenario_path: Path | str, out_dir: Path | str | None = None) -> GenerateResult:
    """Generate `packs/<deal_id>/` (or `<out_dir>/<deal_id>/`) from a scenario file."""
    sc = scenario_mod.load(scenario_path)
    table_problems = names_mod.check_table()
    if table_problems:
        raise PackError("name table problems: " + "; ".join(table_problems))
    bf, run = demo_modules()
    pack_root = (Path(out_dir) if out_dir is not None else PACKS_DIR) / sc.deal_id
    if pack_root.exists():
        shutil.rmtree(pack_root)
    pack_root.mkdir(parents=True)
    envelope = Envelope(scenario_id=sc.deal_id, seed=sc.seed)
    manifest = PackManifest(pack_root, envelope)

    # 1. intake -------------------------------------------------------------------
    files = _build_intake(sc, envelope)
    for f in files:
        env = envelope.model_copy(update={"created_from": [f"scenario:{sc.deal_id}#lab.intake_docs.{f.artifact_key}"]})
        written = write_txt(pack_root / f.relpath, "\n".join(f.body_lines), env, manifest=manifest)
        f.sha256 = written.sha256
        if (pack_root / f.relpath).read_text(encoding="utf-8") != f.text:
            raise PackError(f"{f.relpath}: written text differs from the self-checked text")
    request_rows = _document_request_rows(sc, files)
    checklist_lines = [
        "# Document request checklist (housing sector playbook)",
        "",
        f"Generated from `build_pilot_onboarding_workflow({sc.lab['sector_playbook_key']!r}).document_request_list`"
        " (src/munipal/services/pilot_onboarding.py:202-207) mapped through"
        " `playbook.required_artifacts[*].display_name -> artifact_key`"
        " (src/munipal/services/sector_playbooks.py::_HOUSING_ARTIFACTS).",
        "",
        "| # | Requested document | Level | artifact_key | status in this pack |",
        "|---|---|---|---|---|",
    ]
    for i, row in enumerate(request_rows, start=1):
        checklist_lines.append(f"| {i} | {row['request']} | {row['level']} | `{row['artifact_key']}` | {row['status']} |")
    write_md(
        pack_root / INTAKE_DIR / WELCOME_FOLDER / "document-request-checklist.md",
        "\n".join(checklist_lines),
        envelope.model_copy(update={"created_from": ["src/munipal/services/pilot_onboarding.py::build_pilot_onboarding_workflow('housing').document_request_list"]}),
        manifest=manifest,
    )
    intake_manifest = {
        "upload_order": [
            {
                "order": f.order,
                "path": f.relpath,
                "artifact_key": f.artifact_key,
                "display_name": f.display_name,
                "requirement_level": f.requirement_level,
                "folder": f.folder,
                "expected_paths": f.paths,
                "labels": f.labels,
                "sha256": f.sha256,
                "content_type": "text/plain",
            }
            for f in files
        ],
        "dropped": [
            {
                "artifact_key": key,
                "status": "absent_by_scenario",
                "reason": "knob drop_required_artifact",
                "paths": list(sc.dropped_intake_paths),
            }
            for key in sc.dropped_artifacts
        ],
        "self_check": {
            "mode": "per-artifact (one extraction job per intake artifact; target_schema_paths = that artifact's expected_paths)",
            "extractor": "munipal.services.extraction.rules_based_extractor.RulesBasedExtractor (offline, no LLM)",
            "chunk_text": "the whole file as uploaded, envelope and legend lines included",
            "int_compared_paths": sorted(INT_COMPARED_PATHS),
            "result": "pass",
        },
        "workspace_folders": list(_OPERATOR_WORKSPACE_FOLDERS),
    }
    write_json(
        pack_root / INTAKE_DIR / "intake-manifest.json",
        intake_manifest,
        envelope.model_copy(update={"created_from": [f"scenario:{sc.deal_id}#lab.intake_docs"]}),
        manifest=manifest,
    )
    for key in sc.dropped_artifacts:
        manifest.add_absent(artifact_key=key, reason="knob drop_required_artifact")

    # 2. closing documents (the single copy; reused demo constants) --------------------
    for name, body in bf.DOCUMENTS.items():
        relpath = f"{CLOSING_DIR}/{name}"
        count, heading = _emma_allowance(relpath)
        written = write_md(
            pack_root / relpath,
            body,
            envelope.model_copy(update={"created_from": [f"fulfillment/demo/build_fixtures.py::DOCUMENTS[{name!r}]"]}),
            emma_allowed=count,
            manifest=manifest,
        )
        if heading is not None:
            _assert_token_under_heading(written.path.read_text(encoding="utf-8"), heading, count, relpath)
    for doc_type, reason in STANDARD_DOCS_NOT_CARRIED:
        manifest.add_absent(type=doc_type, reason=reason)

    # 3. post-close evidence ---------------------------------------------------------
    approved_rows: list[dict[str, str]] = []
    for row in bf.APPROVED:
        rec = dict(zip(bf.APPROVED_FIELDS, row, strict=True))
        rec["obligation"] = scrub_platform_token(rec["obligation"])
        rec["recipient"] = scrub_platform_token(rec["recipient"])
        approved_rows.append(rec)
    write_csv(
        pack_root / POST_CLOSE_DIR / "approved-inputs.csv",
        list(bf.APPROVED_FIELDS),
        approved_rows,
        envelope.model_copy(update={"created_from": ["fulfillment/demo/build_fixtures.py::APPROVED (columns obligation, recipient scrubbed of the MSRB platform token)"]}),
        manifest=manifest,
    )
    write_md(
        pack_root / POST_CLOSE_DIR / bf.REF,
        bf.APPROVAL_NOTE,
        envelope.model_copy(update={"created_from": ["fulfillment/demo/build_fixtures.py::APPROVAL_NOTE"]}),
        manifest=manifest,
    )
    name_map = _vault_name_map(bf, run)
    late_afs = bool(sc.lab.get("knobs", {}).get("late_afs"))
    uncarried_fys = {
        str(a["fy"]) for a in (sc.data.get("disclosure") or {}).get("afs") or [] if not a.get("posted")
    }
    vault_written = 0
    for fname, title, filed, recipient in bf.VAULT:
        stem = fname[:-4] if fname.endswith(".txt") else fname
        if stem not in name_map:
            raise PackError(f"vault file {fname!r} matches no rendered evidence_pattern")
        ob_id, pattern, due, tokens = name_map[stem]
        if late_afs and pattern in AFS_LINKED_PATTERNS and tokens["fy"] in uncarried_fys:
            manifest.add_absent(
                vault_file=f"{POST_CLOSE_DIR}/{VAULT_DIR}/{stem}.txt",
                obligation_id=ob_id,
                reason="knob late_afs; afs posting not carried",
            )
            continue
        write_vault_txt(
            pack_root / POST_CLOSE_DIR / VAULT_DIR / f"{stem}.txt",
            f"SYNTHETIC EVIDENCE FILE - {title}",
            f"Filed/delivered: {filed}\nRecipient: {scrub_platform_token(recipient)}",
            envelope.model_copy(
                update={
                    "created_from": [
                        f"fulfillment/demo/build_fixtures.py::VAULT[{fname!r}]",
                        f"approved-inputs.csv:{ob_id} evidence_pattern {pattern!r} rendered with run.py::period_tokens for approved due {due}",
                    ]
                }
            ),
            manifest=manifest,
        )
        vault_written += 1
    demo_stems = {fname[:-4] for fname, *_ in bf.VAULT}
    for stem, (ob_id, pattern, due, _tokens) in sorted(name_map.items()):
        if stem in demo_stems:
            continue
        if pattern.startswith("rebate-calc-"):
            reason = f"first Computation Date {due[:4]}; asof {sc.asof}"
        elif due <= sc.asof:
            reason = "absent in the demo fixture set (build_fixtures.VAULT); the base's evidence-missing row"
        else:
            continue  # not yet due at asof: nothing is absent, nothing is said
        manifest.add_absent(vault_file=f"{POST_CLOSE_DIR}/{VAULT_DIR}/{stem}.txt", obligation_id=ob_id, reason=reason)
    if not (sc.data.get("disclosure") or {}).get("material_events"):
        manifest.add_absent(type="listed_event_notice", reason="disclosure.material_events is empty in the scenario")

    # 4. BONDI-format emission -------------------------------------------------------
    emission = events_mod.emit(sc.data)
    events_mod.write(emission, pack_root, envelope, manifest)
    events_mod.write_artifact_manifest(pack_root, envelope, manifest)

    # 5. manifest ----------------------------------------------------------------------
    saved = manifest.save()
    audit = _audit_pack(pack_root)
    if audit:
        raise PackError("pack audit failed after write: " + "; ".join(audit))
    return GenerateResult(
        deal_id=sc.deal_id,
        pack_root=pack_root,
        manifest_path=saved.path,
        manifest_sha256=saved.sha256,
        files_written=len(manifest.files),
        intake_files=len(files),
        vault_files=vault_written,
        absent_by_scenario=list(manifest.absent_by_scenario),
        intake_paths_unknown=list(sc.dropped_intake_paths),
    )


def cusip_like_tokens(text: str) -> list[str]:
    """CUSIP-shaped tokens in `text` (empty == clean).

    `law.CUSIP_NEAR_WORD_RE` is applied as is. `law.CUSIP_LIKE_STRICT_RE` (nine upper-alnum
    chars) also matches any nine-letter capital word -- `SYNTHETIC` in the legend -- so a
    strict match counts only when it carries at least one digit (a CUSIP's ninth character
    is a check digit; an all-letter token is never a CUSIP).
    """
    hits = [m.group(0) for m in law.CUSIP_NEAR_WORD_RE.finditer(text)]
    hits += [
        m.group(0)
        for m in law.CUSIP_LIKE_STRICT_RE.finditer(text)
        if any(ch.isdigit() for ch in m.group(0))
    ]
    return hits


def _audit_pack(pack_root: Path) -> list[str]:
    """Every file stamped, listed and clean; the platform token only where pinned."""
    from labkit.provenance import audit_file

    problems: list[str] = []
    listed = {e["path"]: e for e in PackManifest.load(pack_root)["files"]}
    on_disk = {p.relative_to(pack_root).as_posix() for p in pack_root.rglob("*") if p.is_file()}
    on_disk.discard(law.PACK_MANIFEST_NAME)
    for missing in sorted(set(listed) - on_disk):
        problems.append(f"manifest lists {missing} but it is not on disk")
    for orphan in sorted(on_disk - set(listed)):
        problems.append(f"{orphan} on disk but not in the manifest")
    for rel in sorted(on_disk & set(listed)):
        path = pack_root / rel
        if sha256_file(path) != listed[rel]["sha256"]:
            problems.append(f"{rel}: sha256 differs from the manifest")
        allowed, _ = _emma_allowance(rel)
        problems += [f"{rel}: {p}" for p in audit_file(path, emma_allowed=allowed)]
        text = path.read_text(encoding="utf-8")
        problems += [f"{rel}: CUSIP-like token {t!r}" for t in cusip_like_tokens(text)]
        if law.FORBIDDEN_SOURCES_RE.search(text):
            problems.append(f"{rel}: forbidden source token")
        for phrase in law.BLOCKLIST_PHRASES:
            if law.blocklist_hits(text, (phrase,)):
                problems.append(f"{rel}: blocklisted phrase {phrase!r}")
    return problems


# --------------------------------------------------------------------------------------
# Pins and the BONDI format transcription
# --------------------------------------------------------------------------------------


def write_pins(pack_manifest_sha256: dict[str, str]) -> WrittenFile:
    payload = {
        "run_py_path": "fulfillment/demo/run.py",
        "run_py_sha256": sha256_file(RUN_PY_PATH),
        "build_fixtures_path": "fulfillment/demo/build_fixtures.py",
        "build_fixtures_sha256": sha256_file(BUILD_FIXTURES_PATH),
        "bondi_format_json_path": "lab/twin-bfms/fixtures/bondi-reference/format.json",
        "bondi_format_json_sha256": sha256_file(FORMAT_JSON_PATH) if FORMAT_JSON_PATH.is_file() else "absent",
        "pack_manifest_sha256": dict(sorted(pack_manifest_sha256.items())),
        "note": "drift alarm: a change to either demo file or to format.json must be followed by a deliberate pack regeneration",
    }
    return write_json(PINS_PATH, payload, Envelope(scenario_id="SYN-LAB-PINS", seed=0, created_from=["labkit/generate_pack.py::write_pins"]))


def _literal_assign(tree: ast.Module, name: str) -> Any:
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            return ast.literal_eval(node.value)
    raise PackError(f"generate.py: no module-level literal assignment {name}")


def _fieldnames(tree: ast.Module) -> list[str]:
    for node in ast.walk(tree):
        if isinstance(node, ast.keyword) and node.arg == "fieldnames":
            return list(ast.literal_eval(node.value))
    raise PackError("generate.py: DictWriter fieldnames not found")


def transcribe_bondi_format(generate_py: Path) -> dict[str, Any]:
    """Transcribe the emission format from generate.py by ast (never executed)."""
    source = generate_py.read_bytes()
    tree = ast.parse(source.decode("utf-8"))
    core = _literal_assign(tree, "STATION_EVENTS_CORE")
    by_pole = _literal_assign(tree, "STATION_EVENTS_BY_POLE")
    post = _literal_assign(tree, "STATION_EVENTS_POST")
    poles = list(_literal_assign(tree, "SALE_POLES"))
    header = _fieldnames(tree)
    if tuple(header) != law.EVENT_LOG_HEADER:
        raise PackError(f"generate.py header {header} != law.EVENT_LOG_HEADER")
    constants = {n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str)}
    missing = [s for s in law.BONDI_EVENT_STATUSES if s not in constants]
    if missing:
        raise PackError(f"generate.py does not spell status(es) {missing}")
    rows = lambda items: [{"station": s, "event": e, "actor_role": r} for s, e, r in items]  # noqa: E731
    stations = sorted({s for s, _e, _r in [*core, *post, *(x for rs in by_pole.values() for x in rs)]})
    if stations != sorted(law.BONDI_STATIONS):
        raise PackError(f"generate.py stations {stations} != law.BONDI_STATIONS")
    return {
        "source_path_windows": BONDI_GENERATE_WINDOWS_PATH,
        "source_path_wsl": str(scenario_mod.bondi_root() / BONDI_GENERATE_REL),
        "source_sha256": sha256_bytes(source),
        "transcribed_on": TRANSCRIPTION_DATE,
        "method": "ast.literal_eval of the module-level constants STATION_EVENTS_CORE, STATION_EVENTS_BY_POLE, STATION_EVENTS_POST, SALE_POLES and the DictWriter fieldnames; generate.py was never executed and is never imported",
        "not_transcribed": "the date offsets (SCENARIO DRESSING) and the Form 8038 due-date helper: the lab never computes a date",
        "event_log_header": header,
        "stations": list(law.BONDI_STATIONS),
        "sale_poles": poles,
        "station_events_core": rows(core),
        "station_events_by_pole": {pole: rows(items) for pole, items in by_pole.items()},
        "station_events_post": rows(post),
        "event_statuses": list(law.BONDI_EVENT_STATUSES),
        "hold_statuses": list(law.HOLD_STATUSES),
        "constraint_statuses": list(law.CONSTRAINT_STATUSES),
        "lab_extension_events": sorted(law.LAB_EXTENSION_EVENTS),
    }


def write_bondi_reference() -> tuple[WrittenFile, WrittenFile]:
    generate_py = scenario_mod.bondi_root() / BONDI_GENERATE_REL
    if not generate_py.is_file():
        raise PackError(f"BONDI generate.py absent or dehydrated at {generate_py}")
    fmt = transcribe_bondi_format(generate_py)
    env = Envelope(scenario_id="SYN-BONDI-FORMAT-REF", seed=0, created_from=[BONDI_GENERATE_WINDOWS_PATH])
    fmt_file = write_json(FORMAT_JSON_PATH, fmt, env)
    body = "\n".join(
        [
            "# BONDI emission-format reference (transcription, not a run)",
            "",
            "twin-bfms is a label, not a claim (DEC-009 section 9.8).",
            "",
            "## What this folder holds",
            "",
            "`format.json` transcribes the EMISSION FORMAT of the BONDI synthetic-issuance runner:",
            "the `event_log.csv` header, the six station names, the event names per sale-method pole",
            "with their actor roles, and the status vocabulary. Nothing else.",
            "",
            "## Source",
            "",
            f"- path (Windows): `{BONDI_GENERATE_WINDOWS_PATH}`",
            f"- path (WSL): `{fmt['source_path_wsl']}`",
            f"- sha256 of generate.py at transcription: `{fmt['source_sha256']}`",
            f"- transcribed on: {TRANSCRIPTION_DATE} (a provenance record; not a scenario date)",
            "- method: `labkit/generate_pack.py::transcribe_bondi_format` -- `ast.literal_eval` of the",
            "  module-level constants `STATION_EVENTS_CORE`, `STATION_EVENTS_BY_POLE`, `STATION_EVENTS_POST`,",
            "  `SALE_POLES` and the `DictWriter` field names. generate.py was NEVER executed, imported,",
            "  copied or vendored (COS working paper 2026-09-10, section 3.3: consume the format, never fork).",
            "",
            "## What is deliberately NOT transcribed",
            "",
            "- the pre-close date offsets (\"SCENARIO DRESSING\") and the Form 8038 due-date helper: the lab never",
            "  computes a date; every date in a lab event log is a scenario literal (brief rule 4).",
            "- BONDI's scenario files and outputs (one calibration scenario carries real names).",
            "",
            "## How the fence uses it",
            "",
            "`tests/unit/test_lab_bondi_format.py::test_lab_bondi_emission_format` checks every",
            "`packs/*/bondi/event_log.csv` against `format.json`; when the OneDrive file is present it",
            "also ast-parses the same constants from `generate.py` and compares them with `format.json`",
            "(drift alarm, pin key `bondi_format_json_sha256`); when absent or dehydrated it skips that",
            "half with a reason. It never runs generate.py.",
            "",
            "## Ownership",
            "",
            "BONDI owns the engine contract; Arthur owns the eventual port into `MUNI-PAL/synth/`.",
            "The lab depends on the emission format only and emits its own log with",
            "`lab/twin-bfms/labkit/events.py`.",
        ]
    )
    prov_file = write_md(FORMAT_PROVENANCE_PATH, body, env.model_copy(update={"created_from": ["labkit/generate_pack.py::write_bondi_reference"]}))
    return fmt_file, prov_file


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def _print_result(res: GenerateResult) -> None:
    print(f"{res.deal_id}: {res.files_written} files ({res.intake_files} intake, {res.vault_files} vault) -> {res.pack_root}")
    print(f"  PACK-MANIFEST.json sha256 {res.manifest_sha256}")
    for entry in res.absent_by_scenario:
        print("  absent_by_scenario: " + json.dumps(entry, sort_keys=True))
    if res.intake_paths_unknown:
        print(f"  intake paths with no line (expected unknown): {res.intake_paths_unknown}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--scenario", help="scenario json (deal-v0 + lab block)")
    parser.add_argument("--out", help="output directory (pack goes to <out>/<deal_id>); default packs/")
    parser.add_argument("--all", action="store_true", help="generate the three committed scenarios and packs/_pins.json")
    parser.add_argument("--bondi-reference", action="store_true", help="write fixtures/bondi-reference/{format.json,PROVENANCE.md}")
    args = parser.parse_args(argv)
    try:
        if args.bondi_reference:
            fmt_file, prov_file = write_bondi_reference()
            print(f"wrote {fmt_file.path} ({fmt_file.sha256}) and {prov_file.path}")
        if args.all:
            shas: dict[str, str] = {}
            for deal_id in COMMITTED_SCENARIOS:
                res = generate(scenario_mod.SCENARIOS_DIR / f"{deal_id}.synthetic.json", args.out)
                _print_result(res)
                shas[deal_id] = res.manifest_sha256
            if args.out is None:
                pins = write_pins(shas)
                print(f"wrote {pins.path} ({pins.sha256})")
        elif args.scenario:
            _print_result(generate(args.scenario, args.out))
        elif not args.bondi_reference:
            parser.error("--scenario, --all or --bondi-reference required")
    except (PackError, ProvenanceViolation, scenario_mod.ScenarioError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())


__all__ = [
    "AFS_LINKED_PATTERNS",
    "COMMITTED_SCENARIOS",
    "FOLDER_BY_ARTIFACT",
    "FORMAT_JSON_PATH",
    "INT_COMPARED_PATHS",
    "PINS_PATH",
    "RENT_ROLL_TABLE",
    "STANDARD_DOCS_NOT_CARRIED",
    "GenerateResult",
    "IntakeFile",
    "PackError",
    "cusip_like_tokens",
    "demo_modules",
    "expected_value",
    "generate",
    "label_for",
    "labels_for",
    "load_module",
    "main",
    "order_lines",
    "readability_check",
    "scrub_platform_token",
    "transcribe_bondi_format",
    "write_bondi_reference",
    "write_pins",
]
