"""Credit Analyzer report generation — produces Markdown + JSON reports."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from .models import (
    BondSizingResult,
    CreditAnalysisResult,
    FiveCsAssessment,
)

logger = logging.getLogger("credit_analyzer.reports")

DEFAULT_REPORT_DIR = Path("reports/credit_analyzer")


def _ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def _slug(name: str) -> str:
    return name.lower().replace(" ", "_").replace("/", "_")[:30]


# ---------------------------------------------------------------------------
# 5 Cs Report
# ---------------------------------------------------------------------------

def generate_five_cs_report(
    result: FiveCsAssessment,
    output_dir: Path | None = None,
) -> tuple[Path, Path]:
    out = _ensure_dir(output_dir or DEFAULT_REPORT_DIR)
    ts = _ts()
    slug = _slug(result.project_name)

    lines = [
        f"# 5 Cs Credit Assessment: {result.project_name}",
        f"",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Composite Score:** {result.composite_score:.1f}/100 ({result.composite_grade})",
        f"**Recommendation:** {result.recommendation.replace('_', ' ').title()}",
        f"",
        f"## Summary",
        f"",
        f"| Dimension | Weight | Score | Grade | Weighted |",
        f"|-----------|-------:|------:|:-----:|---------:|",
    ]

    for cs in [result.character, result.capacity, result.capital, result.collateral, result.conditions]:
        lines.append(
            f"| {cs.dimension} | {cs.weight:.0%} | {cs.score:.0f} | {cs.grade} | {cs.weighted_score:.1f} |"
        )
    lines.append(f"| **Composite** | **100%** | | **{result.composite_grade}** | **{result.composite_score:.1f}** |")
    lines.append("")

    for cs in [result.character, result.capacity, result.capital, result.collateral, result.conditions]:
        lines.append(f"## {cs.dimension} ({cs.score:.0f}/100, {cs.grade})")
        lines.append("")
        if cs.findings:
            lines.append("**Findings:**")
            for f in cs.findings:
                lines.append(f"- {f}")
            lines.append("")
        if cs.risks:
            lines.append("**Risks:**")
            for r in cs.risks:
                lines.append(f"- {r}")
            lines.append("")
        if cs.mitigants:
            lines.append("**Mitigants:**")
            for m in cs.mitigants:
                lines.append(f"- {m}")
            lines.append("")

    if result.conditions_for_approval:
        lines.append("## Conditions for Approval")
        lines.append("")
        for i, c in enumerate(result.conditions_for_approval, 1):
            lines.append(f"{i}. {c}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Muni-Pal Credit Analyzer v0.1.0*")

    md_path = out / f"five_cs_{slug}_{ts}.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")

    json_path = out / f"five_cs_{slug}_{ts}.json"
    json_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    return md_path, json_path


# ---------------------------------------------------------------------------
# Bond Sizing Report
# ---------------------------------------------------------------------------

def generate_sizing_report(
    result: BondSizingResult,
    project_name: str = "Project",
    output_dir: Path | None = None,
) -> tuple[Path, Path]:
    out = _ensure_dir(output_dir or DEFAULT_REPORT_DIR)
    ts = _ts()
    slug = _slug(project_name)

    lines = [
        f"# Bond Sizing Report: {project_name}",
        f"",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"## Sizing Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|------:|",
        f"| Max Par Capacity | ${result.max_par_amount / 1e6:.1f}M |",
        f"| Recommended Par | **${result.recommended_par / 1e6:.1f}M** |",
        f"| Coupon Rate | {result.coupon_rate:.2%} |",
        f"| Maturity | {result.maturity_years:.0f} years |",
        f"| Annual Debt Service | ${result.annual_debt_service / 1e6:.2f}M |",
        f"| Min DSCR | {result.min_dscr:.2f}x |",
        f"| Avg DSCR | {result.avg_dscr:.2f}x |",
        f"| Target DSCR | {result.target_dscr:.2f}x |",
        f"",
        f"## DSCR Sensitivity",
        f"",
        f"| Target DSCR | Max Par |",
        f"|:----------:|--------:|",
        f"| 1.20x | ${result.par_at_dscr_1_20 / 1e6:.1f}M |",
        f"| **1.25x** | **${result.recommended_par / 1e6:.1f}M** |",
        f"| 1.30x | ${result.par_at_dscr_1_30 / 1e6:.1f}M |",
        f"| 1.40x | ${result.par_at_dscr_1_40 / 1e6:.1f}M |",
        f"| 1.50x | ${result.par_at_dscr_1_50 / 1e6:.1f}M |",
        f"",
        f"## Sources & Uses",
        f"",
        f"| Sources | | Uses | |",
        f"|---------|-------:|------|-------:|",
        f"| Bond Proceeds | ${result.recommended_par / 1e6:.1f}M | Project Fund | ${result.project_fund / 1e6:.1f}M |",
        f"| | | DSRF | ${result.debt_service_reserve / 1e6:.2f}M |",
        f"| | | COI | ${result.costs_of_issuance / 1e6:.2f}M |",
        f"| | | UW Discount | ${result.underwriter_discount / 1e6:.2f}M |",
        f"",
    ]

    if result.schedule:
        lines.append("## Debt Service Schedule")
        lines.append("")
        lines.append("| Year | Principal | Interest | Total DS | Net Revenue | DSCR |")
        lines.append("|-----:|----------:|---------:|---------:|------------:|-----:|")
        for yr in result.schedule:
            lines.append(
                f"| {yr.year} | ${yr.principal / 1e6:.2f}M | ${yr.interest / 1e6:.2f}M | "
                f"${yr.total / 1e6:.2f}M | ${yr.net_revenue / 1e6:.2f}M | {yr.dscr:.2f}x |"
            )
        lines.append("")

    if result.sizing_notes:
        lines.append("## Notes")
        lines.append("")
        for note in result.sizing_notes:
            lines.append(f"- {note}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Muni-Pal Credit Analyzer v0.1.0*")

    md_path = out / f"sizing_{slug}_{ts}.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")

    json_path = out / f"sizing_{slug}_{ts}.json"
    json_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    return md_path, json_path


# ---------------------------------------------------------------------------
# Full Analysis Report
# ---------------------------------------------------------------------------

def generate_full_analysis_report(
    result: CreditAnalysisResult,
    output_dir: Path | None = None,
) -> tuple[Path, Path]:
    out = _ensure_dir(output_dir or DEFAULT_REPORT_DIR)
    ts = _ts()
    slug = _slug(result.project_name)

    lines = [
        f"# Credit Analysis Report: {result.project_name}",
        f"",
        f"**Generated:** {(result.analysis_timestamp or datetime.now(timezone.utc)).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Credit Opinion:** {(result.credit_opinion or 'pending').replace('_', ' ').title()}",
        f"",
    ]

    # 5 Cs summary
    if result.five_cs:
        fc = result.five_cs
        lines.append("## 5 Cs Credit Assessment")
        lines.append("")
        lines.append(f"**Composite:** {fc.composite_score:.1f}/100 ({fc.composite_grade}) "
                      f"| **Recommendation:** {fc.recommendation.replace('_', ' ').title()}")
        lines.append("")
        lines.append("| Dimension | Score | Grade |")
        lines.append("|-----------|------:|:-----:|")
        for cs in [fc.character, fc.capacity, fc.capital, fc.collateral, fc.conditions]:
            lines.append(f"| {cs.dimension} ({cs.weight:.0%}) | {cs.score:.0f} | {cs.grade} |")
        lines.append("")

        if fc.key_strengths:
            lines.append("**Strengths:** " + " | ".join(fc.key_strengths[:5]))
            lines.append("")
        if fc.key_risks:
            lines.append("**Risks:** " + " | ".join(fc.key_risks[:5]))
            lines.append("")

    # Bond sizing summary
    if result.bond_sizing and result.bond_sizing.recommended_par > 0:
        bs = result.bond_sizing
        lines.append("## Bond Sizing")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|------:|")
        lines.append(f"| Recommended Par | **${bs.recommended_par / 1e6:.1f}M** |")
        lines.append(f"| Coupon | {bs.coupon_rate:.2%} |")
        lines.append(f"| Maturity | {bs.maturity_years:.0f}yr |")
        lines.append(f"| Min DSCR | {bs.min_dscr:.2f}x |")
        lines.append(f"| Annual DS | ${bs.annual_debt_service / 1e6:.2f}M |")
        lines.append("")

    # Standard Model positioning
    if result.projected_f_score is not None:
        lines.append("## Standard Model Positioning")
        lines.append("")
        lines.append(f"- Fundamental Score (F_i): {result.projected_f_score:.1f}")
        if result.projected_s_omega:
            lines.append(f"- Projected S_Omega: {result.projected_s_omega:.2%}")
        if result.corpus_cri_percentile:
            lines.append(f"- CRI Percentile: {result.corpus_cri_percentile:.0f}th")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Muni-Pal Credit Analyzer v0.1.0*")

    md_path = out / f"analysis_{slug}_{ts}.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")

    json_path = out / f"analysis_{slug}_{ts}.json"
    json_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    return md_path, json_path
