#!/usr/bin/env python3
"""Generate structured questionnaire JSON files from healthcare readiness research.

Run once to produce:
  - questionnaire_healthcare_hospital.json
  - questionnaire_healthcare_senior_living.json
  - questionnaire_healthcare_fqhc_bond.json
  - questionnaire_healthcare_fqhc_cdfi.json
"""

import json
from pathlib import Path

SEED_DIR = Path(__file__).parent


def _item(dim: str, idx: int, cat: str, question: str,
          help_text: str, points: float, lead_time: str,
          agent_assistable: bool, coi_impact: str) -> dict:
    return {
        "item_id": f"{dim}.{idx}",
        "dimension": dim,
        "dimension_label": "",  # filled in later
        "category": cat,
        "question": question,
        "help_text": help_text,
        "points": points,
        "lead_time": lead_time,
        "agent_assistable": agent_assistable,
        "coi_impact": coi_impact,
    }


# ============================================================
# HOSPITAL (47 items, 7 sections)
# ============================================================

HOSPITAL_DIMS = {
    "org_legal": "Organizational & Legal Documents",
    "regulatory": "Regulatory Licenses & Certifications",
    "financial": "Financial Documents & Metrics",
    "clinical_ops": "Clinical & Operational Metrics",
    "capital_project": "Capital Project Documentation",
    "tax_compliance": "Tax & Compliance",
    "rating_market": "Rating Agency & Market Readiness",
}

HOSPITAL_ITEMS = [
    # Section 1: Organizational & Legal Documents
    _item("org_legal", 1, "required", "IRS 501(c)(3) determination letter",
          "Tax-exempt status is foundational; must be current. Reinstatements require extra bond counsel diligence.",
          1, "Already in hand (6-18 mo if new entity)", False, "HIGH"),
    _item("org_legal", 2, "required", "Articles of Incorporation & Bylaws",
          "Must be current, reflecting all amendments. Governance gaps add extra bond counsel hours.",
          1, "Already in hand", True, "Medium"),
    _item("org_legal", 3, "required", "Board authorization resolution",
          "Specific to the bond transaction; cannot be pre-approved generically.",
          1, "1-4 weeks", True, "Medium"),
    _item("org_legal", 4, "required", "Management structure chart",
          "Key personnel, reporting lines, affiliated entities.",
          1, "1-2 weeks", True, "Low"),
    _item("org_legal", 5, "required", "Certificate of Good Standing",
          "Must be current within 60-90 days of closing. State-dependent processing time.",
          1, "1-2 weeks", True, "Low"),
    _item("org_legal", 6, "recommended", "All affiliate/subsidiary organizational docs",
          "Required if affiliate is obligated group member or has pledged assets.",
          1, "2-4 weeks", True, "Medium"),
    _item("org_legal", 7, "recommended", "Management agreement (if external manager)",
          "Subordination provisions critical for lender protection. Management structures raise OS disclosure complexity.",
          1, "8-16 weeks to negotiate", False, "HIGH"),
    _item("org_legal", 8, "required", "Existing debt schedule & bond documents",
          "Every outstanding bond must be reviewed for cross-covenant compliance.",
          1, "1-2 weeks", True, "HIGH"),
    _item("org_legal", 9, "required", "List of all pending litigation",
          "Must include all claims > materiality threshold (typically $1M or 1% of revenue).",
          1, "1-2 weeks", False, "HIGH"),
    _item("org_legal", 10, "required", "Insurance certificates",
          "General liability, property, professional liability (malpractice), D&O.",
          1, "1 week", True, "Low"),
    _item("org_legal", 11, "recommended", "HIPAA compliance attestation",
          "Required by some bond counsel; always noted in Risk Factors.",
          1, "2-4 weeks", False, "Medium"),

    # Section 2: Regulatory Licenses & Certifications
    _item("regulatory", 1, "required", "State hospital operating license",
          "Annual renewal; must be current through projected closing date. Lapsed license = deal collapse.",
          1, "Already in hand (renewal: 30-60 days)", True, "HIGH"),
    _item("regulatory", 2, "required", "Medicare Certification (CMS-855)",
          "Medicare revenue is typically >40% of hospital revenue. Termination proceedings must be disclosed.",
          1, "Already in hand", False, "HIGH"),
    _item("regulatory", 3, "required", "Medicaid Provider Agreement",
          "Must be in good standing in all states where billing occurs.",
          1, "Already in hand", False, "HIGH"),
    _item("regulatory", 4, "recommended", "Joint Commission Accreditation (or DNV/HFAP equivalent)",
          "Many lenders require JCAHO; unaccredited hospitals face rating agency scrutiny.",
          1, "Already in hand (triennial survey)", True, "Medium"),
    _item("regulatory", 5, "required", "Certificate of Need (CON)",
          "Required only in CON states (~35 states); varies by project type. Early identification is critical.",
          1, "6-24 months", False, "VERY HIGH"),
    _item("regulatory", 6, "required", "CMS Cost Report (most recent)",
          "Bond counsel and feasibility consultant will review.",
          1, "Already in hand (filed annually)", True, "Medium"),
    _item("regulatory", 7, "recommended", "State Health Department inspection reports",
          "Deficiencies must be disclosed.",
          1, "2-4 weeks", True, "Medium"),
    _item("regulatory", 8, "optional", "DEA registration (if applicable)",
          "Required for controlled substance programs.",
          1, "Already in hand", True, "Low"),
    _item("regulatory", 9, "optional", "CLIA certification (lab)",
          "Required if hospital operates clinical lab.",
          1, "Already in hand", True, "Low"),
    _item("regulatory", 10, "optional", "Radiation program licenses",
          "NRC or state, depending on facility.",
          1, "Already in hand", True, "Low"),

    # Section 3: Financial Documents & Metrics
    _item("financial", 1, "required", "Audited financial statements (3 most recent FYs)",
          "Dated financials create rating agency concern; deal can stall. If FY audit is in progress, timeline risk is significant.",
          1, "Already in hand if audit complete; 90-180 days if waiting", False, "HIGH"),
    _item("financial", 2, "required", "Interim financial statements (YTD, within 60-90 days)",
          "Underwriter and rating agencies require current picture.",
          1, "2-4 weeks", True, "Medium"),
    _item("financial", 3, "required", "Management's Discussion & Analysis (MD&A)",
          "Key narrative connecting numbers to strategy.",
          1, "2-4 weeks", True, "Medium"),
    _item("financial", 4, "required", "5-year financial projections",
          "Must align with feasibility study if one is required. Weak projections = more feasibility study work = higher fees.",
          1, "4-8 weeks", True, "HIGH"),
    _item("financial", 5, "required", "Payor mix analysis (by revenue source)",
          "Medicare %, Medicaid %, commercial, self-pay; trend over 3 years.",
          1, "1-2 weeks", True, "Medium"),
    _item("financial", 6, "required", "Medicare/Medicaid reimbursement trend analysis",
          "Required in OS; rating agencies scrutinize payment reform exposure.",
          1, "2-3 weeks", True, "Medium"),
    _item("financial", 7, "recommended", "Accounts receivable aging & days outstanding",
          "Indicator of billing efficiency.",
          1, "1-2 weeks", True, "Low"),
    _item("financial", 8, "required", "Days cash on hand (DCOH) calculation",
          "Below 100 DCOH raises significant questions. Rating agencies set thresholds; investment-grade typically requires 150+ DCOH.",
          1, "1 week", True, "HIGH"),
    _item("financial", 9, "required", "Debt service coverage ratio (DSCR) — historical",
          "Historical DSCR below 1.25x = rating pressure = higher fees. Must be calculated on existing AND pro-forma basis.",
          1, "1 week", True, "HIGH"),
    _item("financial", 10, "required", "Operating margin trend (3 years)",
          "Negative or declining trend requires narrative explanation.",
          1, "1 week", True, "Medium"),
    _item("financial", 11, "required", "Capital expenditure history and plan",
          "Bond proceeds source-and-uses alignment.",
          1, "1-2 weeks", True, "Medium"),
    _item("financial", 12, "required", "Debt-to-capitalization ratio",
          "Leverage indicator; compares to sector benchmarks.",
          1, "1 week", True, "Medium"),
    _item("financial", 13, "required", "Existing rate covenant compliance",
          "If existing covenants have been breached (or are at risk), deal is complicated. Waiver process = extra bond counsel + existing bondholder negotiations.",
          1, "1-2 weeks", True, "HIGH"),

    # Section 4: Clinical & Operational Metrics
    _item("clinical_ops", 1, "required", "Average daily census (ADC) — 3-year trend",
          "Core utilization metric; disclosed in OS.",
          1, "1 week", True, "Medium"),
    _item("clinical_ops", 2, "required", "Occupancy rates (inpatient, ICU) — 3-year trend",
          "Volume indicator.",
          1, "1 week", True, "Medium"),
    _item("clinical_ops", 3, "required", "Case mix index (CMI) — 3-year trend",
          "Acuity and revenue intensity indicator.",
          1, "1 week", True, "Medium"),
    _item("clinical_ops", 4, "required", "Outpatient visit volumes — 3-year trend",
          "Outpatient shift narrative is required.",
          1, "1 week", True, "Medium"),
    _item("clinical_ops", 5, "recommended", "Surgical case volume — 3-year trend",
          "High-margin services; supports revenue projections.",
          1, "1 week", True, "Low"),
    _item("clinical_ops", 6, "required", "Emergency department visits — 3-year trend",
          "Volume and capacity indicator.",
          1, "1 week", True, "Low"),
    _item("clinical_ops", 7, "required", "Medical staff composition (FTE physicians, employed vs. independent)",
          "Physician enterprise stability is a rating factor. Turnover or alignment issues must be disclosed.",
          1, "1-2 weeks", True, "Medium"),
    _item("clinical_ops", 8, "recommended", "Staffing levels and turnover (nursing, key clinical)",
          "Post-COVID; agency/travel nurse cost exposure is disclosed.",
          1, "2 weeks", True, "Low"),
    _item("clinical_ops", 9, "recommended", "Quality metrics (mortality, readmissions, HAI rates)",
          "Comparative benchmarks; reputational and regulatory risk signals.",
          1, "2 weeks", True, "Low"),

    # Section 5: Capital Project Documentation
    _item("capital_project", 1, "required", "Feasibility study (independent consultant)",
          "Required for most new money deals; may be waived on refinancing-only. Cost is $40K-$120K+; scope is driven by data quality provided.",
          1, "8-16 weeks from engagement", False, "VERY HIGH"),
    _item("capital_project", 2, "required", "Project cost estimate (independent cost estimator or contractor)",
          "Must match sources & uses in OS. Underestimated project costs = budget overruns = bondholder concern.",
          1, "4-8 weeks", False, "HIGH"),
    _item("capital_project", 3, "required", "Architect/engineer contract and plans",
          "Required at appropriate design stage (typically schematic at bond issuance).",
          1, "Already underway or 4-12 months if early stage", False, "Medium"),
    _item("capital_project", 4, "recommended", "Construction contract (GMP or fixed-price preferred)",
          "Open-ended contracts require additional disclosure and contingency. GMP preferred.",
          1, "4-12 weeks if not yet engaged", False, "Medium"),
    _item("capital_project", 5, "required", "Site control documentation (title, lease, easements)",
          "Must demonstrate clear site control before closing.",
          1, "4-6 weeks", True, "Medium"),
    _item("capital_project", 6, "required", "Environmental assessment — Phase I ESA",
          "Early Phase I prevents surprise delays. Phase II (if triggered) adds 3-6 months.",
          1, "4-8 weeks", False, "HIGH"),
    _item("capital_project", 7, "required", "Environmental assessment — Phase II ESA (if triggered)",
          "Required only if Phase I identifies recognized environmental conditions. Deal delays, remediation costs, title insurance complications.",
          1, "3-6 months if triggered", False, "VERY HIGH"),
    _item("capital_project", 8, "required", "Appraisal of mortgaged property",
          "Required if mortgage security; must meet FIRREA standards.",
          1, "4-6 weeks", False, "Medium"),
    _item("capital_project", 9, "required", "Title insurance commitment",
          "Required for mortgage security deals.",
          1, "2-4 weeks", False, "Low"),
    _item("capital_project", 10, "required", "Zoning compliance letter / entitlements",
          "Zoning issues trigger OS risk factor disclosures and possible deal restructuring.",
          1, "2-4 weeks", True, "Medium"),
    _item("capital_project", 11, "required", "Certificate of Occupancy (existing facilities)",
          "Must be current and consistent with licensed use.",
          1, "Already in hand", True, "Low"),
    _item("capital_project", 12, "recommended", "Master facility plan",
          "Provides strategic context for capital project.",
          1, "Already in hand (update: 2-4 weeks)", True, "Low"),
    _item("capital_project", 13, "recommended", "Equipment list and specifications (if equipment-heavy project)",
          "Affects sources & uses allocation.",
          1, "2-4 weeks", True, "Low"),

    # Section 6: Tax & Compliance
    _item("tax_compliance", 1, "required", "IRS Form 990 (3 most recent years)",
          "Public document; bond counsel reviews for consistency with financial disclosures.",
          1, "Already in hand", True, "Low"),
    _item("tax_compliance", 2, "required", "Property tax exemption documentation",
          "Required where hospital claims exemption; challenges must be disclosed.",
          1, "Already in hand", True, "Medium"),
    _item("tax_compliance", 3, "recommended", "Sales tax exemption certificate",
          "Relevant for capital project purchasing.",
          1, "Already in hand", True, "Low"),
    _item("tax_compliance", 4, "required", "Federal arbitrage compliance certifications (if refunding)",
          "Complex arbitrage issues add bond counsel fees.",
          1, "2-4 weeks", False, "Medium"),
    _item("tax_compliance", 5, "required", "Prior bond tax compliance records (rebate, yield reduction)",
          "Prior non-compliance is a significant issue.",
          1, "Already in hand", True, "HIGH"),
    _item("tax_compliance", 6, "recommended", "501(c)(3) conflict of interest policy",
          "IRS governance standard; bond counsel may request.",
          1, "Already in hand", True, "Low"),
    _item("tax_compliance", 7, "required", "Executive compensation documentation",
          "Unusual compensation structures disclosed in OS. Pull from 990, board minutes.",
          1, "1 week", True, "Medium"),

    # Section 7: Rating Agency & Market Readiness
    _item("rating_market", 1, "required", "Rating agency presentation package",
          "Most impactful single item for deal economics. Poorly prepared presentations = lower initial rating = higher interest cost.",
          1, "4-8 weeks", True, "HIGH"),
    _item("rating_market", 2, "recommended", "Prior rating agency reports & outstanding surveillance items",
          "Unresolved surveillance flags = additional rating agency work.",
          1, "Already in hand", True, "Medium"),
    _item("rating_market", 3, "required", "Strategic plan (3-5 year)",
          "Required for rating narrative; key for feasibility study consistency. Must align with financial projections.",
          1, "Already in hand (update: 2-4 weeks)", True, "Medium"),
    _item("rating_market", 4, "recommended", "Market share analysis (by service line and geography)",
          "Rating agencies assess competitive position. Feasibility consultant will prepare but hospital data needed.",
          1, "2-4 weeks", True, "Medium"),
    _item("rating_market", 5, "recommended", "Physician recruitment plan",
          "Supports volume projections; required for growing programs.",
          1, "1-2 weeks", True, "Low"),
    _item("rating_market", 6, "optional", "Community benefit documentation",
          "Relevant for community relations; sometimes cited in OS narrative.",
          1, "Already in hand", True, "Low"),
]


# ============================================================
# SENIOR LIVING / CCRC (72 items, 7 sections)
# ============================================================

CCRC_DIMS = {
    "org_legal": "Organizational & Legal Documents",
    "regulatory": "Regulatory Licenses & Certifications",
    "financial": "Financial Documents & Metrics",
    "occupancy_demographics": "Occupancy, Waitlist & Demographic Metrics",
    "capital_project": "Capital Project Documentation",
    "tax_compliance": "Tax & Compliance",
    "rating_market": "Rating Agency & Market Readiness",
}

CCRC_ITEMS = [
    # Section 1: Organizational & Legal (12 items)
    _item("org_legal", 1, "required", "IRS 501(c)(3) determination letter",
          "Tax-exempt status foundational.", 1, "Already in hand", False, "HIGH"),
    _item("org_legal", 2, "required", "Articles of Incorporation & Bylaws",
          "Must reflect CCRC governance structure; some states require specific CCRC board composition.", 1, "Already in hand", True, "Medium"),
    _item("org_legal", 3, "required", "Board authorization resolution",
          "Must authorize specific bond transaction.", 1, "1-4 weeks", True, "Medium"),
    _item("org_legal", 4, "required", "Management structure chart",
          "Key: identify whether management is internal or third-party.", 1, "1-2 weeks", True, "Low"),
    _item("org_legal", 5, "required", "Certificate of Good Standing",
          "State-dependent.", 1, "1-2 weeks", True, "Low"),
    _item("org_legal", 6, "required", "Management agreement (if third-party manager)",
          "Third-party management is more common in senior living than hospitals. Fee structure, termination rights, and subordination provisions are heavily scrutinized.", 1, "8-16 weeks to negotiate", False, "VERY HIGH"),
    _item("org_legal", 7, "required", "Existing debt schedule & bond documents",
          "Cross-covenant compliance; entrance fee pledge mechanics.", 1, "1-2 weeks", True, "HIGH"),
    _item("org_legal", 8, "required", "List of all pending litigation",
          "Senior living litigation often includes resident contract disputes, wrongful death, elder abuse allegations.", 1, "1-2 weeks", False, "HIGH"),
    _item("org_legal", 9, "required", "Insurance certificates",
          "General liability, property, professional liability, D&O, workers' comp; abuse/molestation coverage increasingly required.", 1, "1 week", True, "Low"),
    _item("org_legal", 10, "required", "Continuing Care / Residency Agreements (all contract types)",
          "Contract types (Type A/B/C/fee-for-service) define the financial model. Bond counsel must review all forms. Changes to contract terms can require bondholder consent.", 1, "Already in hand", True, "VERY HIGH"),
    _item("org_legal", 11, "required", "Entrance fee refund policy documentation",
          "Refund obligations are a major balance sheet liability. Refund queue length and refund-to-new-entrance-fee timing drives cash flow projections.", 1, "Already in hand", True, "VERY HIGH"),
    _item("org_legal", 12, "required", "Resident handbook / disclosure statement",
          "Required in most states with CCRC regulation. Must be consistent with residency agreements and OS disclosures.", 1, "Already in hand", True, "Medium"),

    # Section 2: Regulatory Licenses & Certifications (11 items)
    _item("regulatory", 1, "required", "State CCRC license / Certificate of Authority",
          "~38 states regulate CCRCs specifically. Lapsed CCRC license = deal cannot close. License conditions (e.g., escrow requirements) affect deal structure.", 1, "Already in hand (renewal: 60-90 days)", True, "VERY HIGH"),
    _item("regulatory", 2, "required", "State CCRC annual filing / disclosure filing",
          "Most CCRC states require annual financial disclosure to residents and regulators. Delinquency is disclosed in OS.", 1, "Already in hand (annual)", True, "HIGH"),
    _item("regulatory", 3, "required", "State assisted living license",
          "Required if facility includes assisted living beds/units. Separate from CCRC license in most states.", 1, "Already in hand", True, "HIGH"),
    _item("regulatory", 4, "required", "Skilled nursing facility (SNF) license",
          "Required if facility includes SNF beds. Subject to state survey and CMS certification.", 1, "Already in hand", True, "HIGH"),
    _item("regulatory", 5, "required", "Medicare Certification (SNF component)",
          "Required only for SNF component. Medicare revenue is typically <10% of CCRC total revenue but certification is required for SNF operation.", 1, "Already in hand", False, "HIGH"),
    _item("regulatory", 6, "required", "Medicaid Provider Agreement (SNF component)",
          "Some CCRCs do not accept Medicaid. If they do, agreement must be current.", 1, "Already in hand", False, "Medium"),
    _item("regulatory", 7, "required", "Certificate of Need (CON)",
          "Required in CON states for new beds/units. Senior living CON thresholds and categories vary significantly by state. Some states exempt independent living from CON.", 1, "6-24 months", False, "VERY HIGH"),
    _item("regulatory", 8, "required", "Fire marshal / life safety inspection reports",
          "Must demonstrate compliance; deficiencies disclosed in OS.", 1, "Already in hand (annual)", True, "Medium"),
    _item("regulatory", 9, "required", "State CCRC escrow / reserve fund compliance",
          "Many states require entrance fee escrow or operating reserve minimums. Non-compliance can trigger regulatory action and deal delays.", 1, "Already in hand", True, "HIGH"),
    _item("regulatory", 10, "required", "Food service / health department permits",
          "Standard but must be current.", 1, "Already in hand", True, "Low"),
    _item("regulatory", 11, "optional", "DEA / pharmacy licenses (if on-site pharmacy)",
          "Applicable to larger CCRCs with on-site pharmacy.", 1, "Already in hand", True, "Low"),

    # Section 3: Financial Documents & Metrics (15 items)
    _item("financial", 1, "required", "Audited financial statements (3 most recent FYs)",
          "Must follow FASB ASC 954 (healthcare) and reflect entrance fee accounting properly.", 1, "Already in hand or 90-180 days", False, "HIGH"),
    _item("financial", 2, "required", "Interim financial statements (YTD)",
          "Underwriter and rating agency requirement.", 1, "2-4 weeks", True, "Medium"),
    _item("financial", 3, "required", "Actuarial feasibility study",
          "Required for new community start-ups and most expansion projects. Cost: $75K-$200K+. Data quality provided to actuary directly controls scope and cost.", 1, "12-20 weeks", False, "VERY HIGH"),
    _item("financial", 4, "required", "Actuarial study of future service obligations",
          "FASB ASC 954-440: obligation to provide future services to current residents. Must be performed by qualified actuary. Understated obligation = restatement risk.", 1, "8-16 weeks", False, "HIGH"),
    _item("financial", 5, "required", "Financial feasibility study (market demand component)",
          "May be combined with actuarial study. Market penetration rates, competitive analysis, age-qualified household counts are heavily agent-assistable.", 1, "8-16 weeks", True, "HIGH"),
    _item("financial", 6, "required", "5-year financial projections",
          "Must incorporate entrance fee turnover assumptions, healthcare cost inflation, refund obligation timing.", 1, "4-8 weeks", True, "HIGH"),
    _item("financial", 7, "required", "Entrance fee cash flow model",
          "Projects entrance fee receipts, refund payments, net entrance fee cash flow. Depends on turnover rate, resale timing, refund policy, and waitlist depth. Central credit model for CCRCs.", 1, "2-4 weeks", True, "VERY HIGH"),
    _item("financial", 8, "required", "Entrance fee pricing history and current schedule",
          "Pricing power evidence; trend analysis supports projection credibility.", 1, "1 week", True, "HIGH"),
    _item("financial", 9, "required", "Refund obligation liability schedule",
          "Must quantify total refund exposure by contract type and remaining term.", 1, "1-2 weeks", True, "HIGH"),
    _item("financial", 10, "required", "Days cash on hand (DCOH) calculation",
          "CCRC threshold: 200+ DCOH typically expected by rating agencies (higher than hospitals due to entrance fee obligation coverage).", 1, "1 week", True, "HIGH"),
    _item("financial", 11, "required", "Debt service coverage ratio (DSCR) — historical",
          "Must be calculated with and without entrance fees (revenue-only DSCR vs. total DSCR). Rating agencies weight revenue-only DSCR more heavily.", 1, "1 week", True, "HIGH"),
    _item("financial", 12, "required", "Operating ratio (operating expenses / total revenue)",
          "CCRC benchmark: <95% for investment grade.", 1, "1 week", True, "Medium"),
    _item("financial", 13, "recommended", "Monthly service fee history and comparison",
          "Fee increase history demonstrates pricing power; competitive comparison validates positioning.", 1, "1 week", True, "Medium"),
    _item("financial", 14, "required", "Capital expenditure history and deferred maintenance assessment",
          "Aging physical plant is a major CCRC credit concern; deferred maintenance backlog must be quantified.", 1, "1-2 weeks", True, "HIGH"),
    _item("financial", 15, "recommended", "Accounts receivable aging",
          "Less critical than hospitals (entrance fees are pre-paid) but SNF/AL AR matters.", 1, "1 week", True, "Low"),

    # Section 4: Occupancy, Waitlist & Demographic Metrics (9 items)
    _item("occupancy_demographics", 1, "required", "Occupancy rates by level of care (IL, AL, SNF, Memory Care) — 3-year trend",
          "The single most important operating metric for CCRCs. Must be segmented. IL occupancy <90% is a red flag.", 1, "1 week", True, "HIGH"),
    _item("occupancy_demographics", 2, "required", "Waitlist depth and conversion rate",
          "Waitlist expressed as ratio to annual turnover. 2:1+ waitlist is strong. Conversion rate (deposits to move-ins) validates demand.", 1, "1 week", True, "HIGH"),
    _item("occupancy_demographics", 3, "required", "Unit turnover rate by level of care — 3-year trend",
          "Drives entrance fee cash flow projections. Typical IL turnover: 8-12% annually (mortality + transfers to higher care).", 1, "1 week", True, "HIGH"),
    _item("occupancy_demographics", 4, "required", "Resident age and health profile (census demographics)",
          "Average entry age, current average age, distribution by level of care. Actuarial projections depend on this data.", 1, "1-2 weeks", True, "HIGH"),
    _item("occupancy_demographics", 5, "recommended", "Healthcare transfer rates (IL→AL, AL→SNF, IL→SNF)",
          "Internal transfer patterns inform actuarial assumptions and healthcare cost projections.", 1, "1-2 weeks", True, "Medium"),
    _item("occupancy_demographics", 6, "required", "Market penetration rate analysis",
          "Age-qualified households in primary market area (PMA) vs. CCRC capacity. Penetration rates >10-12% raise demand sustainability concerns.", 1, "2-3 weeks", True, "HIGH"),
    _item("occupancy_demographics", 7, "required", "Competitive community analysis",
          "All CCRCs within PMA: pricing, occupancy, wait times, contract types, expansion plans.", 1, "2-4 weeks", True, "HIGH"),
    _item("occupancy_demographics", 8, "required", "Absorption / fill-up schedule (expansion projects)",
          "Required for new construction or expansion. Must demonstrate realistic fill-up pace. Optimistic absorption assumptions are the #1 cause of CCRC bond defaults.", 1, "2-4 weeks", True, "VERY HIGH"),
    _item("occupancy_demographics", 9, "required", "Pre-sale / priority deposit count and conversion pipeline",
          "Required for expansion/new community deals. Most underwriters require 50-70% pre-sales before pricing. Deposit-to-contract conversion rate is critical.", 1, "1 week", True, "VERY HIGH"),

    # Section 5: Capital Project Documentation (11 items)
    _item("capital_project", 1, "required", "Project cost estimate (independent)",
          "Must include FF&E, site work, contingency. Senior living construction costs $300K-$600K+ per unit.", 1, "4-8 weeks", False, "HIGH"),
    _item("capital_project", 2, "required", "Architect/engineer contract and plans",
          "Age-in-place design requirements add complexity vs. hospital construction.", 1, "Already underway or 4-12 months", False, "Medium"),
    _item("capital_project", 3, "recommended", "Construction contract (GMP preferred)",
          "Open-ended construction risk is a primary CCRC bond default driver.", 1, "4-12 weeks", False, "Medium"),
    _item("capital_project", 4, "required", "Site control documentation",
          "Title, easements, access.", 1, "4-6 weeks", True, "Medium"),
    _item("capital_project", 5, "required", "Environmental assessment — Phase I ESA",
          "Same as hospital framework.", 1, "4-8 weeks", False, "HIGH"),
    _item("capital_project", 6, "required", "Environmental assessment — Phase II ESA (if triggered)",
          "Same as hospital framework.", 1, "3-6 months if triggered", False, "VERY HIGH"),
    _item("capital_project", 7, "required", "Appraisal of facility/property",
          "CCRC appraisals are complex — going-concern value vs. real estate value; specialized appraisers needed.", 1, "4-8 weeks", False, "Medium"),
    _item("capital_project", 8, "recommended", "Interior design / model unit plans",
          "Marketing tool for pre-sales; demonstrated in prospective resident presentations.", 1, "Already underway", False, "Low"),
    _item("capital_project", 9, "required", "Marketing / pre-sales plan and budget",
          "Required for expansion. Marketing costs can be $2M-$5M+ for new community. Plan must align with absorption schedule.", 1, "Already in hand", True, "HIGH"),
    _item("capital_project", 10, "required", "Zoning compliance / entitlements",
          "Age-restricted zoning, height restrictions, parking requirements.", 1, "2-4 weeks", True, "Medium"),
    _item("capital_project", 11, "required", "State regulatory approval for new/expanded CCRC",
          "Beyond CON — many states require separate CCRC expansion approval from insurance/aging department. Some require pre-opening escrow deposits.", 1, "3-12 months", False, "VERY HIGH"),

    # Section 6: Tax & Compliance (8 items)
    _item("tax_compliance", 1, "required", "IRS Form 990 (3 most recent years)",
          "Public document; bond counsel reviews.", 1, "Already in hand", True, "Low"),
    _item("tax_compliance", 2, "required", "Property tax exemption documentation",
          "CCRCs have mixed-use (residential + healthcare); some states tax the independent living component. Partial exemption disputes are common and must be disclosed.", 1, "Already in hand", True, "HIGH"),
    _item("tax_compliance", 3, "recommended", "Entrance fee tax treatment analysis",
          "IRC §213(d) medical expense deduction calculation for residents; marketing differentiator and resident disclosure item.", 1, "2-4 weeks", False, "Medium"),
    _item("tax_compliance", 4, "required", "Federal arbitrage compliance (if refunding)",
          "Same as hospital.", 1, "2-4 weeks", False, "Medium"),
    _item("tax_compliance", 5, "required", "Prior bond tax compliance records",
          "Same as hospital.", 1, "Already in hand", True, "HIGH"),
    _item("tax_compliance", 6, "recommended", "501(c)(3) conflict of interest policy",
          "IRS governance standard.", 1, "Already in hand", True, "Low"),
    _item("tax_compliance", 7, "required", "Executive compensation documentation",
          "Pull from 990; compare to peer benchmarks.", 1, "1 week", True, "Medium"),
    _item("tax_compliance", 8, "recommended", "Resident financial qualification / credit screening policies",
          "Underwriter diligence item; inconsistent screening = occupancy risk.", 1, "Already in hand", True, "Medium"),

    # Section 7: Rating Agency & Market Readiness (6 items)
    _item("rating_market", 1, "required", "Rating agency presentation package",
          "Fitch is the dominant CCRC rater. Presentation must include actuarial data, entrance fee model, occupancy history, waitlist, competitive analysis.", 1, "4-8 weeks", True, "HIGH"),
    _item("rating_market", 2, "recommended", "Prior rating reports & surveillance items",
          "Unresolved items delay rating assignment.", 1, "Already in hand", True, "Medium"),
    _item("rating_market", 3, "required", "Strategic plan (3-5 year)",
          "Must address aging infrastructure, market positioning, care continuum strategy.", 1, "Already in hand", True, "Medium"),
    _item("rating_market", 4, "recommended", "Resident satisfaction survey results",
          "Supports occupancy/waitlist narrative; NRC Health or internal surveys.", 1, "Already in hand", True, "Medium"),
    _item("rating_market", 5, "required", "Expansion/renovation master plan",
          "Required if bond is for capital project. Must demonstrate phased approach and market demand support.", 1, "Already in hand", True, "Medium"),
    _item("rating_market", 6, "required", "Actuarial certification letter (for existing obligations)",
          "Rating agencies require independent actuarial verification that future service obligations are adequately funded.", 1, "2-4 weeks", False, "HIGH"),
]


# ============================================================
# FQHC Track A — Revenue Bond (58 items, 8 sections)
# ============================================================

FQHC_BOND_DIMS = {
    "federal_compliance": "Federal Compliance & HRSA Status",
    "org_legal": "Organizational & Legal Documents",
    "regulatory": "Regulatory Licenses & Certifications",
    "financial": "Financial Documents & Metrics",
    "capital_project": "Capital Project Readiness",
    "compliance_reporting": "Compliance & Reporting Infrastructure",
    "bond_specific": "Revenue Bond Specific Items",
}

FQHC_BOND_ITEMS = [
    # Section 1: Federal Compliance & HRSA Status (8 items)
    _item("federal_compliance", 1, "required", "Active HRSA Section 330 grant (H80 award)",
          "Without active 330 grant, FQHC designation is lost; no access to any FQHC capital programs. Notice of Award (NOA) must be current.", 1, "Already in hand (12-18 mo if new)", False, "VERY HIGH"),
    _item("federal_compliance", 2, "required", "HRSA scope of project (approved service sites & services)",
          "Capital project must be within approved scope; unapproved scope = Change in Scope (CIS) required before closing.", 1, "Already in hand; CIS: 2-6 months", True, "HIGH"),
    _item("federal_compliance", 3, "required", "BPHC Operational Site Visit (OSV) results — most recent",
          "Outstanding conditions = deal risk. Progressive Action (PA) or Immediate Action (IA) findings must be disclosed.", 1, "Already in hand (triennial)", True, "HIGH"),
    _item("federal_compliance", 4, "required", "UDS (Uniform Data System) reports — 3 most recent years",
          "Includes patient demographics, clinical quality measures, financial data, staffing. UDS data quality issues raise management capacity questions.", 1, "Already in hand (annual)", True, "Medium"),
    _item("federal_compliance", 5, "required", "Section 330 compliance checklist — 19 program requirements",
          "Includes: governance (51% patient board), sliding fee, QI/QA program, after-hours coverage, etc. Non-compliance can lead to grant conditions or termination.", 1, "2-4 weeks", True, "HIGH"),
    _item("federal_compliance", 6, "required", "FTCA (Federal Tort Claims Act) deeming letter — current",
          "FTCA deeming = free malpractice coverage; loss of deeming = must purchase insurance = major cost increase. Renewed annually.", 1, "Already in hand (annual renewal)", True, "HIGH"),
    _item("federal_compliance", 7, "recommended", "340B Drug Pricing Program enrollment and compliance",
          "340B savings are material revenue; loss of eligibility is a disclosed risk factor. HRSA 340B audits have increased.", 1, "Already in hand; audit results 1-2 weeks", True, "Medium"),
    _item("federal_compliance", 8, "required", "Health Center Program Compliance Manual attestation",
          "Annual attestation required by HRSA; false attestation risk.", 1, "1-2 weeks", True, "Medium"),

    # Section 2: Organizational & Legal (11 items)
    _item("org_legal", 1, "required", "IRS 501(c)(3) determination letter",
          "Tax-exempt status foundational for all FQHC financing channels.", 1, "Already in hand", False, "HIGH"),
    _item("org_legal", 2, "required", "Board composition documentation — 51%+ patient majority",
          "Section 330 requires majority patient-governed board; non-compliance = grant risk.", 1, "Already in hand", True, "HIGH"),
    _item("org_legal", 3, "required", "Board member conflict of interest disclosures",
          "HRSA requires annual COI disclosures; more stringent than typical nonprofit.", 1, "1-2 weeks", True, "Medium"),
    _item("org_legal", 4, "required", "Articles of Incorporation & Bylaws",
          "Must reflect FQHC governance requirements (patient board majority, sliding fee commitment).", 1, "Already in hand", True, "Medium"),
    _item("org_legal", 5, "required", "Board authorization resolution for financing",
          "Specific to the financing transaction.", 1, "1-4 weeks", True, "Medium"),
    _item("org_legal", 6, "required", "Certificate of Good Standing (state)",
          "Current within 60-90 days.", 1, "1-2 weeks", True, "Low"),
    _item("org_legal", 7, "required", "Collaborative/contractual agreements for required services",
          "Section 330 requires all primary care services be available; some via contracts.", 1, "Already in hand; new: 4-8 weeks", False, "Medium"),
    _item("org_legal", 8, "required", "Existing debt schedule & loan documents",
          "Prior HRSA facility grants may have reverter clauses; existing CDFI loans have covenants.", 1, "1-2 weeks", True, "HIGH"),
    _item("org_legal", 9, "required", "HRSA property records & federal interest inventory",
          "Assets built/renovated with federal funds have federal interest; encumbrance complicates financing. Must be calculated and disclosed.", 1, "2-4 weeks", True, "VERY HIGH"),
    _item("org_legal", 10, "required", "List of pending litigation",
          "FTCA-covered claims handled by HHS, but non-FTCA claims must be disclosed.", 1, "1-2 weeks", False, "Medium"),
    _item("org_legal", 11, "required", "Insurance certificates",
          "If FTCA-deemed: professional liability covered by federal government; still need property, D&O, general liability.", 1, "1 week", True, "Low"),

    # Section 3: Regulatory Licenses & Certifications (10 items)
    _item("regulatory", 1, "required", "State FQHC/clinic license (varies by state)",
          "Not all states require separate FQHC license; verify state-specific requirements.", 1, "Already in hand", True, "HIGH"),
    _item("regulatory", 2, "required", "Medicare enrollment (CMS-855A/B)",
          "FQHC-specific Medicare PPS rate is typically higher than fee-for-service; loss = major revenue hit.", 1, "Already in hand", False, "HIGH"),
    _item("regulatory", 3, "required", "Medicaid enrollment & managed care contracts",
          "Medicaid is ~45% of FQHC revenue; managed care wrap-around PPS payments are complex.", 1, "Already in hand", False, "HIGH"),
    _item("regulatory", 4, "required", "CLIA certificate(s) for all lab sites",
          "FQHCs typically have waived CLIA certificates at multiple sites.", 1, "Already in hand", True, "Low"),
    _item("regulatory", 5, "required", "DEA registration(s) — all applicable sites",
          "Required if controlled substances dispensed or administered.", 1, "Already in hand", True, "Low"),
    _item("regulatory", 6, "required", "State pharmacy license (if on-site pharmacy/340B)",
          "Required for FQHCs with in-house pharmacies or 340B contract pharmacy arrangements.", 1, "Already in hand", True, "Medium"),
    _item("regulatory", 7, "recommended", "Behavioral health licensure (if integrated BH services)",
          "Many FQHCs provide integrated behavioral health; state licensure requirements vary.", 1, "Already in hand or 3-6 months", True, "Medium"),
    _item("regulatory", 8, "optional", "Dental program licensure/permits",
          "~70% of FQHCs provide dental services; facility requirements vary by state.", 1, "Already in hand", True, "Low"),
    _item("regulatory", 9, "optional", "Joint Commission / AAAHC accreditation",
          "Unlike hospitals, FQHC accreditation is not required for reimbursement. Some FQHCs pursue AAAHC voluntarily.", 1, "6-12 months if new", True, "Low"),
    _item("regulatory", 10, "recommended", "State Health Department inspection reports",
          "Site-specific inspection results for all locations.", 1, "2-4 weeks", True, "Medium"),

    # Section 4: Financial Documents & Metrics (13 items)
    _item("financial", 1, "required", "Audited financial statements (3 most recent FYs)",
          "FQHCs with >$750K in federal expenditures require Single Audit (2 CFR 200).", 1, "Already in hand", False, "HIGH"),
    _item("financial", 2, "required", "Single Audit findings & corrective action plans",
          "Material weakness or significant deficiency on H80 grant program = deal risk.", 1, "Already in hand", True, "VERY HIGH"),
    _item("financial", 3, "required", "Interim financial statements (YTD)",
          "Must be within 60-90 days of application/closing.", 1, "2-4 weeks", True, "Medium"),
    _item("financial", 4, "required", "UDS financial tables — revenue by source",
          "Granular view: grants, Medicaid, Medicare, commercial, self-pay, 340B revenue.", 1, "Already in hand", True, "Medium"),
    _item("financial", 5, "required", "HRSA grant budget vs. actuals (most recent budget period)",
          "Available from HRSA Electronic Handbooks (EHB); demonstrates fiscal management.", 1, "1-2 weeks", True, "Medium"),
    _item("financial", 6, "required", "5-year financial projections",
          "Must account for: federal grant volatility, Medicaid policy risk, PPS rate changes.", 1, "4-8 weeks", True, "HIGH"),
    _item("financial", 7, "required", "Payor mix with FQHC-specific detail",
          "Must separate: Medicaid FFS, Medicaid managed care (wrap), Medicare, commercial, sliding fee, uninsured, grant-supported.", 1, "1-2 weeks", True, "HIGH"),
    _item("financial", 8, "required", "Sliding Fee Discount Program (SFDP) schedule & utilization",
          "Required by Section 330; sliding fee patients are a cost center offset by grants. Schedule A-D; % of patients at each discount tier.", 1, "Already in hand", True, "Medium"),
    _item("financial", 9, "required", "Days cash on hand (DCOH)",
          "FQHC median DCOH is ~60-90 days (lower than hospitals); <45 days is concerning.", 1, "1 week", True, "HIGH"),
    _item("financial", 10, "required", "Operating margin (with and without grant revenue)",
          "Many FQHCs are operationally unprofitable without federal grants; must show both.", 1, "1 week", True, "HIGH"),
    _item("financial", 11, "recommended", "Cost per patient/visit trends",
          "UDS provides visit counts; key efficiency metric for CDFI/NMTC applications.", 1, "1-2 weeks", True, "Medium"),
    _item("financial", 12, "required", "Debt service coverage ratio (DSCR) — historical",
          "FQHC DSCR thresholds may be lower than hospital (1.10-1.20x acceptable for CDFI); 1.25x+ for bonds.", 1, "1 week", True, "HIGH"),
    _item("financial", 13, "required", "Capital expenditure history and plan",
          "Must align with approved scope of project.", 1, "1-2 weeks", True, "Medium"),

    # Section 5: Capital Project Readiness (11 items)
    _item("capital_project", 1, "required", "HRSA Change in Scope (CIS) approval — if adding new site",
          "Cannot open new site without HRSA CIS approval; financing may close before CIS is granted [risk].", 1, "2-6 months", False, "VERY HIGH"),
    _item("capital_project", 2, "required", "HRSA prior approval for capital expenditure >$250K (if grant-funded)",
          "Required when using grant funds for capital; threshold is $250K for equipment, any amount for construction.", 1, "1-3 months", True, "HIGH"),
    _item("capital_project", 3, "required", "Architectural/engineering plans",
          "Must comply with ADA, state building codes, and HRSA facility standards.", 1, "8-16 weeks", False, "Medium"),
    _item("capital_project", 4, "required", "Community needs assessment (CNA) — current",
          "Required by Section 330; demonstrates need for expanded capacity. HRSA requires CNA every 3 years.", 1, "Already in hand or 3-6 months", True, "HIGH"),
    _item("capital_project", 5, "required", "Environmental review (Phase I ESA)",
          "Contamination = deal delay + cost increase.", 1, "4-8 weeks", True, "HIGH"),
    _item("capital_project", 6, "required", "NEPA environmental review (if federal funds involved)",
          "HRSA requires NEPA compliance for federally-funded construction; often overlooked. Even partial federal funding triggers NEPA.", 1, "2-6 months", False, "HIGH"),
    _item("capital_project", 7, "required", "Title report / title insurance commitment",
          "Standard for bond-financed real estate.", 1, "2-4 weeks", True, "Medium"),
    _item("capital_project", 8, "required", "Site control documentation (lease, deed, option)",
          "Many FQHCs lease space; lease terms must support financing timeline. Landlord estoppel may be required.", 1, "Already in hand or 4-8 weeks", True, "HIGH"),
    _item("capital_project", 9, "required", "Construction budget and timeline",
          "Must align with HRSA budget if grant-funded.", 1, "2-4 weeks", True, "Medium"),
    _item("capital_project", 10, "required", "NMTC allocation letter (if NMTC financing)",
          "NMTC allocations are highly competitive; allocation is the gate.", 1, "6-12 months (competitive)", True, "HIGH"),
    _item("capital_project", 11, "required", "CDFI loan application package",
          "Varies by CDFI; CHC Capital Fund, Capital Link, IFF, LISC are common FQHC CDFIs.", 1, "4-8 weeks", True, "Medium"),

    # Section 6: Compliance & Reporting Infrastructure (8 items)
    _item("compliance_reporting", 1, "required", "HRSA Electronic Handbooks (EHB) access & current submissions",
          "EHB is HRSA's portal for all grant management; delinquent submissions = grant risk.", 1, "Already in hand", True, "Medium"),
    _item("compliance_reporting", 2, "required", "Quality Improvement/Quality Assurance (QI/QA) plan — current",
          "Required by Section 330; absence signals management weakness.", 1, "Already in hand or 2-4 weeks", True, "Medium"),
    _item("compliance_reporting", 3, "required", "Health center governing board meeting minutes (12 months)",
          "Demonstrates active governance; HRSA reviews during OSV.", 1, "Already in hand", True, "Medium"),
    _item("compliance_reporting", 4, "required", "Credentialing and privileging records for all providers",
          "Required by Section 330; gaps are common OSV findings.", 1, "Already in hand", True, "Medium"),
    _item("compliance_reporting", 5, "recommended", "HIPAA compliance documentation",
          "Risk analysis, policies, breach history.", 1, "2-4 weeks", False, "Medium"),
    _item("compliance_reporting", 6, "recommended", "Patient-Centered Medical Home (PCMH) recognition",
          "Not required but increasingly valued by funders. NCQA PCMH recognition is common among FQHCs.", 1, "Already in hand or 6-12 months", True, "Low"),
    _item("compliance_reporting", 7, "recommended", "Value-based payment readiness assessment",
          "Relevant for demonstrating financial sustainability beyond fee-for-service.", 1, "2-4 weeks", True, "Medium"),
    _item("compliance_reporting", 8, "required", "Continuing disclosure compliance history",
          "Only applicable if FQHC has prior bond issuance. Check your public municipal disclosure filings.", 1, "1-2 weeks", True, "Medium"),

    # Section 7: Revenue Bond Specific Items (7 items)
    _item("bond_specific", 1, "required", "Feasibility study (or financial advisory report)",
          "Typically $40K-$100K; required for unrated or lower-rated deals.", 1, "6-12 weeks", False, "HIGH"),
    _item("bond_specific", 2, "recommended", "Rating agency presentation (if seeking rating)",
          "Rated FQHC deal is extremely rare; most proceed unrated.", 1, "3-5 weeks", True, "HIGH"),
    _item("bond_specific", 3, "required", "HRSA approval for use of federally-funded property as collateral",
          "Federal interest in property may prevent pledging as bond security. HRSA must approve.", 1, "2-4 months", False, "VERY HIGH"),
    _item("bond_specific", 4, "required", "Bond counsel engagement",
          "Orrick has FQHC experience (On Lok deals).", 1, "1-2 weeks", True, "Medium"),
    _item("bond_specific", 5, "required", "Underwriter selection or bank selection (private placement)",
          "Limited FQHC deal experience in market.", 1, "2-4 weeks", True, "Medium"),
    _item("bond_specific", 6, "required", "Conduit issuer application (state HFA)",
          "CHFFA, MassDevelopment, NJHCFFA all have FQHC programs; application requirements vary.", 1, "2-6 weeks", True, "Medium"),
    _item("bond_specific", 7, "required", "Preliminary Official Statement drafting",
          "FQHC-specific disclosures: HRSA grant status, 330 compliance, FTCA deeming, 340B, patient governance.", 1, "4-8 weeks", True, "HIGH"),
]


# ============================================================
# FQHC Track B — CDFI/NMTC (38 items, shared sections + Track B)
# ============================================================

FQHC_CDFI_DIMS = {
    "federal_compliance": "Federal Compliance & HRSA Status",
    "org_legal": "Organizational & Legal Documents",
    "regulatory": "Regulatory Licenses & Certifications",
    "financial": "Financial Documents & Metrics",
    "capital_project": "Capital Project Readiness",
    "compliance_reporting": "Compliance & Reporting Infrastructure",
    "cdfi_nmtc": "CDFI / NMTC Application Items",
}

FQHC_CDFI_ITEMS = [
    # Section 1: Federal Compliance (same core items, 8)
    _item("federal_compliance", 1, "required", "Active HRSA Section 330 grant (H80 award)",
          "Without active 330 grant, FQHC designation is lost; no access to FQHC capital programs.", 1, "Already in hand", False, "HIGH"),
    _item("federal_compliance", 2, "required", "HRSA scope of project (approved service sites & services)",
          "Capital project must be within approved scope.", 1, "Already in hand; CIS: 2-6 months", True, "HIGH"),
    _item("federal_compliance", 3, "required", "BPHC Operational Site Visit (OSV) results — most recent",
          "Outstanding conditions flag management risk for CDFI lenders.", 1, "Already in hand (triennial)", True, "Medium"),
    _item("federal_compliance", 4, "required", "UDS reports — 3 most recent years",
          "Core data for CDFI/NMTC applications. Patient demographics, quality measures, financial data.", 1, "Already in hand (annual)", True, "Medium"),
    _item("federal_compliance", 5, "required", "Section 330 compliance checklist — 19 program requirements",
          "CDFI lenders verify compliance as underwriting criterion.", 1, "2-4 weeks", True, "Medium"),
    _item("federal_compliance", 6, "required", "FTCA deeming letter — current",
          "Loss of deeming = insurance cost increase = affects debt service capacity.", 1, "Already in hand (annual)", True, "Medium"),
    _item("federal_compliance", 7, "recommended", "340B Drug Pricing Program enrollment and compliance",
          "340B revenue material for CDFI loan underwriting.", 1, "Already in hand", True, "Medium"),
    _item("federal_compliance", 8, "required", "Health Center Program Compliance Manual attestation",
          "Annual attestation required by HRSA.", 1, "1-2 weeks", True, "Low"),

    # Section 2: Organizational & Legal (8 items — streamlined for CDFI)
    _item("org_legal", 1, "required", "IRS 501(c)(3) determination letter",
          "Required for all FQHC financing channels.", 1, "Already in hand", False, "HIGH"),
    _item("org_legal", 2, "required", "Board composition documentation — 51%+ patient majority",
          "Section 330 requirement; verified by CDFI lenders.", 1, "Already in hand", True, "Medium"),
    _item("org_legal", 3, "required", "Articles of Incorporation & Bylaws",
          "Must reflect FQHC governance requirements.", 1, "Already in hand", True, "Low"),
    _item("org_legal", 4, "required", "Board authorization resolution for financing",
          "Specific to the financing transaction.", 1, "1-4 weeks", True, "Low"),
    _item("org_legal", 5, "required", "Existing debt schedule & loan documents",
          "Prior HRSA facility grants may have reverter clauses.", 1, "1-2 weeks", True, "Medium"),
    _item("org_legal", 6, "required", "HRSA property records & federal interest inventory",
          "Federal interest affects collateral pledging even for CDFI loans.", 1, "2-4 weeks", True, "HIGH"),
    _item("org_legal", 7, "required", "List of pending litigation",
          "Non-FTCA claims must be disclosed to CDFI lenders.", 1, "1-2 weeks", False, "Low"),
    _item("org_legal", 8, "required", "Insurance certificates",
          "Property, D&O, general liability required by CDFI lenders.", 1, "1 week", True, "Low"),

    # Section 3: Regulatory (5 items — key items only for CDFI)
    _item("regulatory", 1, "required", "State FQHC/clinic license",
          "Verify state-specific requirements.", 1, "Already in hand", True, "Medium"),
    _item("regulatory", 2, "required", "Medicare enrollment (CMS-855A/B)",
          "PPS rate revenue is key to debt service capacity.", 1, "Already in hand", False, "HIGH"),
    _item("regulatory", 3, "required", "Medicaid enrollment & managed care contracts",
          "~45% of revenue; CDFI underwriters assess Medicaid concentration risk.", 1, "Already in hand", False, "HIGH"),
    _item("regulatory", 4, "required", "CLIA certificate(s) for all lab sites",
          "Standard compliance verification.", 1, "Already in hand", True, "Low"),
    _item("regulatory", 5, "recommended", "State pharmacy license (if on-site pharmacy/340B)",
          "Required for 340B revenue stream.", 1, "Already in hand", True, "Low"),

    # Section 4: Financial (7 items — CDFI-focused)
    _item("financial", 1, "required", "Audited financial statements (3 most recent FYs) with Single Audit",
          "Single Audit findings on HRSA grants are heavily weighted by CDFI lenders.", 1, "Already in hand", False, "HIGH"),
    _item("financial", 2, "required", "Interim financial statements (YTD)",
          "Within 60-90 days of application.", 1, "2-4 weeks", True, "Medium"),
    _item("financial", 3, "required", "5-year financial projections",
          "Must account for grant volatility and Medicaid policy risk. Below-market CDFI rates improve projections.", 1, "4-8 weeks", True, "HIGH"),
    _item("financial", 4, "required", "Payor mix with FQHC-specific detail",
          "Granular breakdown required for CDFI underwriting.", 1, "1-2 weeks", True, "Medium"),
    _item("financial", 5, "required", "Days cash on hand (DCOH)",
          "CDFI lenders may accept lower DCOH than bond market (45-60 days).", 1, "1 week", True, "Medium"),
    _item("financial", 6, "required", "Operating margin (with and without grant revenue)",
          "Grant-dependent operations are a material risk factor.", 1, "1 week", True, "HIGH"),
    _item("financial", 7, "required", "Debt service coverage ratio (DSCR) — historical",
          "CDFI lenders may accept 1.10-1.20x DSCR (lower than bond market).", 1, "1 week", True, "Medium"),

    # Section 5: Capital Project (3 items — CDFI essentials)
    _item("capital_project", 1, "required", "HRSA Change in Scope (CIS) approval — if adding new site",
          "Hard gate for new site projects.", 1, "2-6 months", False, "HIGH"),
    _item("capital_project", 2, "required", "Community needs assessment (CNA) — current",
          "Core to CDFI/NMTC applications; demonstrates need for expanded capacity.", 1, "Already in hand or 3-6 months", True, "HIGH"),
    _item("capital_project", 3, "required", "Construction budget and timeline",
          "Must align with HRSA budget if any grant-funded component.", 1, "2-4 weeks", True, "Medium"),

    # Section 6: Compliance (no separate section — items covered above)

    # Section 7: CDFI/NMTC Application Items (7 items)
    _item("cdfi_nmtc", 1, "required", "CDFI application narrative (organizational capacity, project impact)",
          "CHC Capital Fund, IFF, LISC, Capital Link have specific formats. Application quality directly affects approval.", 1, "2-4 weeks", True, "Medium"),
    _item("cdfi_nmtc", 2, "required", "Community impact documentation",
          "Census data, health disparities, access metrics. UDS data, HRSA data warehouse, census tract analysis for low-income qualification.", 1, "2-4 weeks", True, "Medium"),
    _item("cdfi_nmtc", 3, "required", "Project pro forma with CDFI/NMTC terms",
          "Below-market rates, NMTC 7-year compliance period, leverage structure.", 1, "2-4 weeks", True, "Medium"),
    _item("cdfi_nmtc", 4, "required", "Low-income census tract qualification documentation (NMTC)",
          "FQHC project site must be in or serve qualifying census tracts. CDFI Fund mapping tool.", 1, "1-2 weeks", True, "Low"),
    _item("cdfi_nmtc", 5, "required", "NMTC CDE application (if seeking new allocation)",
          "Highly competitive (25% approval rate). Only if CDE doesn't already have allocation.", 1, "8-12 weeks", True, "Medium"),
    _item("cdfi_nmtc", 6, "optional", "HRSA grant application for supplemental capital funds",
          "Capital Improvement Program (CIP), ARPA-H, other periodic competitions.", 1, "4-8 weeks per competition", True, "Low"),
    _item("cdfi_nmtc", 7, "optional", "State FQHC capital grant application (if available)",
          "Some states (CA, NJ, MA) have specific FQHC capital programs.", 1, "Varies by state", True, "Low"),
]


def _finalize(items: list[dict], dims: dict[str, str]) -> list[dict]:
    """Fill in dimension_label from the dimension map."""
    for it in items:
        it["dimension_label"] = dims[it["dimension"]]
    return items


def main():
    files = {
        "questionnaire_healthcare_hospital.json": _finalize(HOSPITAL_ITEMS, HOSPITAL_DIMS),
        "questionnaire_healthcare_senior_living.json": _finalize(CCRC_ITEMS, CCRC_DIMS),
        "questionnaire_healthcare_fqhc_bond.json": _finalize(FQHC_BOND_ITEMS, FQHC_BOND_DIMS),
        "questionnaire_healthcare_fqhc_cdfi.json": _finalize(FQHC_CDFI_ITEMS, FQHC_CDFI_DIMS),
    }

    for fname, items in files.items():
        out = SEED_DIR / fname
        with open(out, "w", encoding="utf-8") as f:
            json.dump(items, f, indent=2, ensure_ascii=False)
        # Validate counts
        req = sum(1 for it in items if it["category"] == "required")
        rec = sum(1 for it in items if it["category"] == "recommended")
        opt = sum(1 for it in items if it["category"] == "optional")
        dims_set = set(it["dimension"] for it in items)
        print(f"  {fname}: {len(items)} items ({req}R/{rec}Rec/{opt}O), {len(dims_set)} dimensions")


if __name__ == "__main__":
    main()
